folio-org/ui-finance

package.json
=> Require interfaces from mod-finance.

package.json, src/components/Budget/Budget.js
=> Upgrade to stripes-components 3.0.0

CHANGELOG.md, src/components/Budget/Budget.js, src/components/Budget/BudgetForm.js, src/components/Budget/BudgetView.js, src/components/FiscalYear/FiscalYearForm.js, src/components/FiscalYear/FiscalYearView.js, src/components/Fund/Fund.js, src/components/Fund/FundForm.js, src/components/Fund/FundView.js, src/components/Ledger/Ledger.js, src/components/Ledger/LedgerForm.js, src/components/Ledger/LedgerView.js
* Implement tags into Ledger, Funds, Budget, Fiscal Year and. Ref: UIF-17, UIF-18, UIF-19 and UIF-20.
* Fixed column sorting. Ref: UIF-14 
* Enabled disabled fields in budget view. Ref: UIF-23 
* Fixed fiscal year label mis-match. Ref: UIF-15 
* Fixed fund labels mismatch, moved description input at the bottom in fund form. Ref: UIF-4.
* Fixed mismatch labels and align name and code field grid. Ref: UIF-5. 
* Removed fiscal year start and end date 'readonly' attribute. Ref: UIF-22.
* Fixes typo "Limit Encumbrance Percent" and "Limit Expenditure Percent". ref: UIF-13.
* Added asterisk to required field in Budget. ref: UIF-13.
* Added asterisk and required fiscal year start date and end date. ref: UIF-9.
=> Dev to Master

CHANGELOG.md, src/components/Budget/Budget.js, src/components/Budget/BudgetForm.js, src/components/Budget/BudgetView.js, src/components/FiscalYear/FiscalYear.js, src/components/Fund/FundForm.js, src/components/Ledger/Ledger.js, src/components/Ledger/LedgerForm.js
* fixed gerDerivedStateFromProps error in ledger
* Removed default sorting="name" value to sorting="" form fiscal year
* Updated labels for "Allowable Encumbrance Percentage" and "Allowable Expenditure Percentage".
* Added asterisk to Name label in ledger form.
* Added asterist to all required fields in Funds. Ref: UIF-12.
=> Merge dev to master

CHANGELOG.md, src/components/Budget/BudgetView.js, src/components/FiscalYear/FiscalYearView.js, src/components/Fund/FundView.js, src/components/Ledger/LedgerView.js
https://issues.folio.org/browse/STRIPES-558
=> STRIPES-558 Remove notes helper app

CHANGELOG.md, package.json
* Clean up Fiscal Year name in ledger view and ledger edit. Ref: UIF-8.
* Show percentage in Allowable Encumbrance and Expenditure. Ref: UIF-27.
* Budget totals Allocated, Unavailable and Available: css theming and show calculation results. Ref: UIF-28.
* Change property name "period_start and period_end" to "start_date and end_date". Ref: UIF-24;
* Added asterisk to Name label in ledger form. Ref: UIF-10.
* Added asterist to all required fields in Funds. Ref: UIF-12.
* Fixed funds date field invalid value. Ref: UIF-11.
* Updated labels for "Allowable Encumbrance Percentage" and "Allowable Expenditure Percentage". Ref: UIF-2;
* Implement tags into Ledger, Funds, Budget, Fiscal Year and. Ref: UIF-17, UIF-18, UIF-19 and UIF-20.
* Fixed column sorting. Ref: UIF-14
* Enabled disabled fields …
=> UIF-29 Release v1.1.0

src/components/Ledger/Ledger.js, src/components/Ledger/LedgerView.js
Fixed loading data when trying to access edit page directly
=> UIF-39 Fixed ledger edit data

src/components/Fund/Fund.js, src/components/Fund/FundView.js, src/components/Ledger/LedgerView.js
Fixed getting data when going directly to view and edit fund
=> UIF-40 fund edit and view data

src/components/Budget/BudgetView.js, src/components/FiscalYear/FiscalYear.js, src/components/FiscalYear/FiscalYearView.js, src/components/Ledger/Ledger.js
also removed budgetView.js componentWillMount
=> UIF-42 Fiscal year detailed and edit data

README.md
=> FOLIO-1021 update copyright year

translations/ui-finance/ar.json, translations/ui-finance/en_US.json
=> Update translation strings as of 20190219T224024

translations/ui-finance/es_ES.json
=> Update translation strings as of 20190425T181703

src/components/Budget/BudgetPane.js, src/components/FiscalYear/FiscalYearPane.js, src/components/Fund/FundPane.js, src/components/Ledger/LedgerPane.js, translations/ui-finance/en.json
it needs to change button labels
https://issues.folio.org/browse/UIF-64
added expected labels translation …
=> UIF-64 Change Create/Update Finance buttons

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/zh_CN.json
=> Update translation strings as of 20190429T154045

translations/ui-finance/es_419.json
=> Update translation strings as of 20190501T184815

package.json
https://issues.folio.org/browse/UIF-67
change permissions …
=> UIF-67 Setting visible Finance permissions has no effect

package.json
https://issues.folio.org/browse/UIF-67
add permission 
While it's helpful for reviewers …
=> UIF-67 configuration permissions

package.json
Update Okapi interface versions before release
https://issues.folio.org/browse/UIF-93 …
=> UIF-93 Update Okapi interface versions

translations/ui-finance/zh_CN.json
=> Update translation strings as of 20190729T163855

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/zh_CN.json
=> Update translation strings as of 20190807T131714

translations/ui-finance/it_IT.json
=> Update translation strings as of 20190828T124751

package.json, src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupDetails/GroupInformation/GroupInformation.js, src/Groups/GroupDetails/GroupInformation/index.js, src/Groups/GroupDetails/index.js, src/Groups/Groups.js, src/Groups/GroupsList/GroupsList.js, src/Groups/GroupsList/index.js, src/Groups/constants.js, src/Groups/index.js, src/common/FinanceNavigation/FinanceNavigation.js, src/common/FinanceNavigation/constants.js, src/common/const/api.js, src/common/const/index.js, src/common/const/routes.js, src/common/resources/group.js, src/components/Main/Main.js, test/bigtest/interactors/common/FinanceNavigation.js, test/bigtest/interactors/groups/GroupDetailsInteractor.js, test/bigtest/interactors/groups/GroupsListInteractor.js, test/bigtest/network/config.js, test/bigtest/network/configs/groups.js, test/bigtest/network/factories/group.js, test/bigtest/network/models/group.js, test/bigtest/network/serializers/group.js, test/bigtest/tests/groups/GroupDetails/GroupDetails-test.js, test/bigtest/tests/groups/GroupsList/GroupsList-test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-87 …
=> UIF-87 View fund group record details

package.json, src/Groups/EditGroup/EditGroup.js, src/Groups/EditGroup/index.js, src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupForm/GroupForm.js, src/Groups/GroupForm/index.js, src/Groups/Groups.js, src/Groups/GroupsList/GroupsList.js, src/Groups/constants.js, src/common/const/routes.js, test/bigtest/interactors/common/OptionListInteractor.js, test/bigtest/interactors/groups/GroupFormInteractor.js, test/bigtest/interactors/groups/GroupsListInteractor.js, test/bigtest/network/configs/groups.js, test/bigtest/tests/groups/GroupCreate/GroupCreate-test.js, test/bigtest/tests/groups/GroupDetails/GroupDetails-test.js, test/bigtest/tests/groups/GroupEdit/GroupEdit-test.js, test/bigtest/tests/groups/GroupsList/GroupsList-test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-88
https://issues.folio.org/browse/UIF-89
While it's …
=> UIF-88 UIF-89 - group actions

src/components/Fund/FundsList.js, src/components/Ledger/Ledger.js, src/components/Main/Main.js, src/index.js
to refresh list of items when they're arrived (changed tab)
https://issues.folio.org/browse/UIF-106 …
=> UIF-106 fix refreshes of list

src/components/Ledger/LedgerView/LedgerInformation.js, src/components/Ledger/LedgerView/LedgerView.js
Display numbers (since back-end is ready)
https://issues.folio.org/browse/UIF-84
While …
=> UIF-84 display numbers

src/Transactions/Transfer/TransferAddModal.js, src/Transactions/Transfer/TransferAddModalForm.js, src/components/Budget/BudgetView/BudgetViewContainer.js, test/bigtest/interactors/budgets/BudgetDetails.js, test/bigtest/tests/transactions/addTransfer-test.js
Fix options list for fields `Transfer To` and `Transfer From`
https://issues.folio.org/browse/UIF-79 …
=> UIF-79 CRUD transfer - Fund options

src/components/ConnectionListing/ConnectionListing.js
ACQ Apps: MCL column width updates
https://issues.folio.org/browse/STCOM-590
Remove `columnWidths` prop from MCL …
=> STCOM-590 ACQ Apps: MCL column width updates

src/Transactions/TransactionDetails/TransactionInformation/TransactionInformation.js
Fix tag list displaying
https://issues.folio.org/browse/UIF-101 …
=> UIF-101 fix tags displaying

src/Transactions/CreateTransaction/CreateTransactionModal.js, src/components/Ledger/LedgerView/LedgerFunds.js, src/components/Ledger/LedgerView/LedgerViewContainer.js, test/bigtest/interactors/ledgers/LedgerDetailsInteractor.js, test/bigtest/tests/ledgers/LedgerDetails/LedgerDetails-test.js
fix eslint warnings
While it's helpful for reviewers to help identify potential …
=> fix eslint 2

src/components/Budget/BudgetView/BudgetViewContainer.js
Fix action menu (It does not close after user clicks allocate or transfer but the Modal is displayed underneath)
https://issues.folio.org/browse/UIF-79
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
=> UIF-79 Fix action menu

src/components/FiscalYear/FiscalYearsList/FiscalYearListFilterConfig.js, src/components/FiscalYear/FiscalYearsList/FiscalYearListFilters/FiscalYearListFilters.js, src/components/FiscalYear/FiscalYearsList/FiscalYearListFilters/FiscalYearListFiltersContainer.js, src/components/FiscalYear/FiscalYearsList/FiscalYearListFilters/index.js, src/components/FiscalYear/FiscalYearsList/FiscalYearListSearchConfig.js, src/components/FiscalYear/FiscalYearsList/FiscalYearsList.js, src/components/FiscalYear/constants.js, src/components/Ledger/LedgerList/LedgerList.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-110 …
=> UIF-110 Search and Filter: Search and Filter Fiscal year'

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/zh_CN.json
=> Update translation strings as of 20190927T125508

src/common/const/constants.js, src/components/Ledger/LedgerView/LedgerGroups.js, src/components/Ledger/LedgerView/LedgerView.js, src/components/Ledger/LedgerView/LedgerViewContainer.js, src/components/Ledger/constants.js, translations/ui-finance/en.json
Display group info on ledger record view pane
https://issues.folio.org/browse/UIF-76 …
=> UIF-76 Display group on ledger record view pane

src/Groups/GroupsList/GroupsList.js, src/Groups/GroupsList/GroupsListFilterConfig.js, src/Groups/GroupsList/GroupsListSearchConfig.js, src/Groups/GroupsListFilters/GroupsListFilters.js, src/Groups/GroupsListFilters/GroupsListFiltersContainer.js, src/Groups/GroupsListFilters/index.js, src/Groups/constants.js, translations/ui-finance/en.json
When searching for a specific type of finance record the user must be able to search and filter by specific criteria. In order to find the record they need.
Filters 
- Status
- Acquisition units
Search
- Keyword (search the name and description fields)
- Name
- Code
https://issues.folio.org/browse/UIF-111
Rewrite functional component `GroupsList` into a class component for using common functions for filters and search.
- Are the …
=> UIF-111 Search and Filter "Group"

src/components/Fund/FundListFilterConfig.js, src/components/Fund/FundListFilters/FundListFilters.js, src/components/Fund/FundListFilters/FundListFiltersContainer.js, src/components/Fund/constants.js, translations/ui-finance/en.json
Add Group filter for Funds
https://issues.folio.org/browse/UIF-112
While it's helpful …
=> UIF-112 Group filter for Funds

src/components/Budget/AddBudgetModal/AddBudgetModal.js, src/components/Budget/AddBudgetModal/AddBudgetModalForm.js, src/components/Budget/constants.js
- add validation for required fields
- fix creating a budget name
- fix budger status options …
=> Fix add new Budget form

translations/ui-finance/ar.json
=> Update translation strings as of 20191005T202237

src/Groups/GroupsList/GroupsList.js, src/common/FinanceNavigation/FinanceNavigation.js, src/components/FiscalYear/FiscalYearsList/FiscalYearsList.js, src/components/Fund/FundsList.js, src/components/Ledger/LedgerList/LedgerList.js
Sort Funds alphabetically by default
https://issues.folio.org/browse/UIF-35
While it's …
=> UIF-35 Sort Funds alphabetically by default

src/components/Budget/BudgetForm/BudgetFormContainer.js, src/components/Ledger/EditLedger/EditLedger.js, src/components/Ledger/LedgerList/LedgerList.js
Fix creation new ledger
https://issues.folio.org/browse/UIF-120
also fixed save method on budget from …
=> UIF-120 Fix creation new ledger

package.json, src/Groups/GroupForm/GroupForm.js, src/components/Fund/FundForm/FundForm.js, translations/ui-finance/en.json
Update validation message
https://issues.folio.org/browse/UIF-114?focusedCommentId=62325&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-62325
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UIF-114 Update validation message

src/Transactions/TransactionsList/TransactionsListContainer.js, src/common/FinanceNavigation/FinanceNavigation.js, src/components/Budget/Budget.js, src/components/Fund/Fund.js, src/index.js
=> fix router improts

package.json, src/common/const/api.js, src/common/resources/fund.js, src/components/Fund/FundDetails/FundDetails.js, src/components/Fund/FundDetails/FundDetailsContainer.js, src/components/Fund/FundForm/FundForm.js, src/components/Fund/FundsList.js, src/components/Ledger/LedgerList/LedgerList.js, test/bigtest/network/configs/funds.js
To be able assign Acq untis we need BL API for funds
https://issues.folio.org/browse/UIF-72 …
=> UIF-72 use funds from BL

package.json, src/common/resources/fund.js, src/components/Fund/FundForm/FundForm.js, src/components/Fund/FundForm/FundFormContainer.js, src/components/Fund/FundForm/fetchFunds.js, src/components/Fund/FundsList.js, test/bigtest/interactors/funds/FundForm.js, test/bigtest/network/config.js, test/bigtest/network/configs/fundTypes.js, test/bigtest/network/factories/fundType.js, test/bigtest/network/models/fundType.js, test/bigtest/network/serializers/fundType.js, test/bigtest/tests/funds/EditFund/EditFund-test.js, translations/ui-finance/en.json
also switch to the final form.
Since some "warning" validation for name was added, I've decided we need to implement this on the new api of reac-final-form, because it's a default component for Forms in folio. 
Do not allow the duplication of Fund codes.
https://issues.folio.org/browse/UIF-34
Ideally all of the PRs involved in breaking changes would be …
=> UIF-34 Add name and code validation on Fund form

package.json, src/Groups/GroupDetails/GroupFund/GroupFund.js, src/common/const/api.js, src/components/FiscalYear/FiscalYearDetails/FiscalYearDetails.js, src/components/FiscalYear/FiscalYearsList/FiscalYearsList.js, src/components/Fund/FundDetails/FundDetailsContainer.js, src/components/Fund/FundsList.js, src/components/Ledger/LedgerList/LedgerList.js, src/components/Ledger/LedgerView/LedgerFunds.js, src/components/Ledger/LedgerView/LedgerView.js
use finance business logic module
https://issues.folio.org/browse/UIF-102
While it's …
=> UIF-102 use finance business logic module

src/common/FiscalYearField/FiscalYearField.js, src/common/FiscalYearField/FiscalYearFieldContainer.js, src/common/FiscalYearField/index.js, src/components/Budget/AddBudgetModal/AddBudgetModal.js, src/components/Budget/AddBudgetModal/AddBudgetModalForm.js, src/components/Ledger/LedgerForm/LedgerForm.js, test/bigtest/helpers/setup-application.js, test/bigtest/tests/ledgers/LedgerEdit/LedgerEdit-test.js, translations/ui-finance/en.json
Select fiscal year during ledger creation
https://issues.folio.org/browse/UIF-123
While …
=> UIF-123 select fiscal year on ledger form

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20191101T174958

translations/ui-finance/en.json
Change error message
https://issues.folio.org/browse/UIF-34 …
=> UIF-34 change error message

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20191104T173556

src/components/Fund/FundDetails/FundDetailsContainer.js, src/components/Fund/FundForm/FundFormContainer.js, src/components/Fund/FundsList.js, test/bigtest/tests/funds/DeleteFund/DeleteFund-test.js, test/bigtest/tests/funds/EditFund/EditFund-test.js
Once you have selected a fund from the result list clicking create new button brings up the edit form for that fund.
https://issues.folio.org/browse/UIF-132
- Change structure for getting fund to `get(resources, ['fund', 'records', 0, 'fund'])` based on BE changes (composite-fund)
- add `clientGeneratePk: false` for fund resource to avoid id generation before save
- Do PRs exist for …
=> UIF-132 Cannot access create new fund after selecting a fund

src/components/Budget/constants.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-129 …
=> UIF-129 Add 'inactive' status support to the Budget view/edit screen

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20191106T134035

package.json
Finance perms: Label update
https://issues.folio.org/browse/UIF-131
While it's helpful …
=> UIF-131 Finance perms: Label update

translations/ui-finance/en.json
=> UIF-123 change label

src/components/Fund/FundDetails/FundDetailsContainer.js
Fund: connected ledger and type not displaying in view pane
https://issues.folio.org/browse/UIF-138 …
=> UIF-138 Fund: connected ledger and type not displaying in view pane

src/common/FiscalYearField/FiscalYearField.js, src/common/FiscalYearField/FiscalYearFieldContainer.js, src/components/Ledger/LedgerForm/LedgerForm.js
Pass label to the fiscal's year field
https://issues.folio.org/browse/UIF-123
While it's …
=> UIF-123 pass label to the fiscal year field

src/components/FiscalYear/EditFiscalYear/EditFiscalYear.js, src/components/FiscalYear/FiscalYearsList/FiscalYearsList.js, translations/ui-finance/en.json
Small improvement, handle `genericError` code of back-end errors
https://issues.folio.org/browse/UIF-135 …
=> UIF-135 handle `genericError` code

src/components/Fund/FundDetails/FundDetailsContainer.js, src/components/Fund/FundForm/FundForm.js, src/components/Fund/FundForm/FundFormContainer.js
https://issues.folio.org/browse/UIF-138?focusedCommentId=65081&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-65081 …
=> UIF-138 Fund: add system currency

src/components/Fund/FundForm/FundFormContainer.js, translations/ui-finance/en.json
Improve error messages to the user
https://issues.folio.org/browse/UIF-98
While it's …
=> show proper error message

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20191115T154823

src/components/FiscalYear/FiscalYearsList/FiscalYearsList.js, src/components/Ledger/EditLedger/EditLedger.js, src/components/Ledger/LedgerList/LedgerList.js
=> UIF-124 use param instead of location state

translations/ui-finance/ar.json, translations/ui-finance/fr_FR.json, translations/ui-finance/pt_BR.json
=> Update translation strings as of 20191118T154404

translations/ui-finance/fr_FR.json, translations/ui-finance/it_IT.json
=> Update translation strings as of 20191119T231120

src/components/Fund/FundListFilterConfig.js, src/components/Fund/FundListFilters/FundListFilters.js, src/components/Fund/constants.js
https://issues.folio.org/browse/UIF-127 …
=> UIF-127 Filter Finance fund records by tags

src/components/Ledger/LedgerView/LedgerGroups.js
https://issues.folio.org/browse/UIF-144 …
=> UIF-144 Ledger displaying duplicate groups

src/components/Budget/BudgetView/BudgetInformation.js
Allowable encumbrance and expenditure not showing as a percentage
https://issues.folio.org/browse/UIF-143 …
=> UIF-143 Add percentage sign

src/common/RelatedFunds/RelatedFunds.js, src/common/const/api.js, src/common/resources/fiscalYear.js, src/components/Ledger/LedgerView/LedgerFunds.js, src/components/Ledger/LedgerView/LedgerInformation.js, src/components/Ledger/LedgerView/LedgerView.js, src/components/Ledger/LedgerView/LedgerViewContainer.js, test/bigtest/network/configs/fiscalYears.js, test/bigtest/network/configs/ledgers.js, test/bigtest/tests/ledgers/LedgerDetails/LedgerDetails-test.js, translations/ui-finance/en.json
Ledger view: Fiscal year
* use the new API to fetch current fiscal year for ledger;
* handle errors in fetching ledger's data;
https://issues.folio.org/browse/UIF-141
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> UIF-141 Ledger view: Fiscal year

src/components/Fund/AllocatedFunds/AllocatedFunds.js, src/components/Fund/AllocatedFunds/AllocatedFundsContainer.js, src/components/Fund/AllocatedFunds/index.js, src/components/Fund/FundBudgets/FundBudgets.js, src/components/Fund/FundBudgets/FundBudgetsContainer.js, src/components/Fund/FundBudgets/index.js, src/components/Fund/FundDetails/FundDetails.js, src/components/Fund/FundDetails/FundDetailsContainer.js, src/components/Fund/FundLedger/FundLedger.js, src/components/Fund/FundLedger/FundLedgerContainer.js, src/components/Fund/FundLedger/index.js, src/components/Fund/FundType/FundType.js, src/components/Fund/FundType/FundTypeContainer.js, src/components/Fund/FundType/index.js, test/bigtest/interactors/common/tags/TagsAction.js, test/bigtest/interactors/common/tags/TagsPane.js, test/bigtest/interactors/funds/FundDetails.js, test/bigtest/tests/budgets/details-budget-test.js, test/bigtest/tests/funds/CreteBudget/CreateBudget-test.js, test/bigtest/tests/funds/DeleteFund/DeleteFund-test.js, test/bigtest/tests/funds/EditFund/EditFund-test.js, test/bigtest/tests/funds/FundDetails/FundDetails-test.js, test/bigtest/tests/funds/FundTags/FundTags-test.js
Assign tags to Finance Fund Records
`<Tags>` from `stripes-acq-components`
While it's …
=> UIF-18 Assign tags to Finance Fund Records

src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupDetails/GroupInformation/GroupInformation.js, src/Groups/GroupDetails/utils.js, src/common/const/api.js, src/common/resources/groupSummaries.js, src/common/resources/index.js, test/bigtest/interactors/groups/GroupDetailsInteractor.js, test/bigtest/network/config.js, test/bigtest/network/configs/groupSummaries.js, test/bigtest/network/factories/groupSummary.js, test/bigtest/network/models/groupSummary.js, test/bigtest/network/serializers/groupSummary.js, test/bigtest/tests/groups/GroupDetails/GroupSummaryDetails-test.js
https://issues.folio.org/browse/UIF-107 …
=> UIF-107 Add funds to a Group and calculate the summaries

src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupDetails/GroupFund/GroupFund.js, src/Groups/GroupDetails/GroupInformation/GroupInformation.js, src/common/RelatedFunds/RelatedFunds.js, src/common/utils/getFundToDisplay.js, test/bigtest/tests/ledgers/LedgerDetails/LedgerDetails-test.js, translations/ui-finance/en.json
Update group record view to display related fund totals for the current fiscal year
https://issues.folio.org/browse/UIF-147 …
=> UIF-147 show reltaed funds for group

src/components/Fund/FundForm/FundForm.js, src/components/Fund/FundForm/FundFormContainer.js
fix Cannot edit Fund
basically, used a workaround, the bug is related to the latest changes in final-form
https://issues.folio.org/browse/UIF-142
https://github.com/folio-org/ui-agreements/pull/365
https://github.com/final-form/final-form/issues/300
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIF-142 use workaround to get initial values

src/Groups/GroupDetails/GroupInformation/GroupInformation.js, src/components/ConnectionListing/ConnectionListing.js, src/components/ConnectionListing/css/ConnectionListing.css, translations/ui-finance/en.json
Add end of list mark
https://issues.folio.org/browse/UIF-147 …
=> UIF-147 add end of list mark

src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupDetails/GroupInformation/GroupInformation.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-147 …
=> UIF-147 refresh group summary after FY change

src/Groups/GroupDetails/utils.js, src/components/Ledger/LedgerView/LedgerGroups.js, src/components/Ledger/LedgerView/LedgerView.js, src/components/Ledger/LedgerView/utils.js
https://issues.folio.org/browse/UIF-146 …
=> UIF-146 Update Ledger record view to display related group totals for that year

src/components/Ledger/LedgerView/LedgerFunds.js, src/components/Ledger/LedgerView/LedgerView.js
Update Ledger record view to display related fund totals for that year
https://issues.folio.org/browse/UIF-150 …
=> UIF-150 filter fund by ledgerId

.eslintrc, CHANGELOG.md, PULL_REQUEST_TEMPLATE.md, package.json
* changed PR template
https://issues.folio.org/browse/UIF-104 …
=> Release v1.7.0

CHANGELOG.md, src/components/Fund/FundCurrentBudget/FundCurrentBudgetContainer.js, src/components/Fund/FundCurrentBudget/index.js, src/components/Fund/FundDetails/FundDetailsContainer.js, test/bigtest/tests/funds/CreteCurrentBudget/CreateCurrentBudget-test.js, test/bigtest/tests/funds/EditFund/EditFund-test.js, test/bigtest/tests/funds/FundDetails/FundDetails-test.js, translations/ui-finance/en.json
There can only be one budget per fiscal year and there can only be one current fiscal year. Meaning there should only ever be one current budget for any given fund.
https://issues.folio.org/browse/UIF-154
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> UIF-154 Displaying multiple current budgets at once

CHANGELOG.md, src/components/Ledger/LedgerView/LedgerViewContainer.js
https://issues.folio.org/browse/UIF-159
- [*] There are no breaking changes in this PR. …
=> UIF-159 Ledger not displaying correct totals

PULL_REQUEST_TEMPLATE.md
- [*] There are no breaking changes in this PR. …
=> fix PR template

package.json
https://issues.folio.org/browse/UIF-155 …
=> UIF-155 add permissions to CRUD fund-types in finance settings

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIF-155 …
=> Release v1.7.1

CHANGELOG.md, src/common/FiscalYearField/FiscalYearFieldContainer.js, src/components/Budget/AddBudgetModal/AddBudgetModal.js, src/components/Budget/AddBudgetModal/AddBudgetModalForm.js, src/components/Budget/AddBudgetModal/index.js, src/components/Fund/FundCurrentBudget/FundCurrentBudgetContainer.js, src/components/Fund/FundDetails/FundDetailsContainer.js, test/bigtest/interactors/funds/FundDetails.js, test/bigtest/tests/funds/CreteCurrentBudget/CreateCurrentBudget-test.js
Update create current budget
https://issues.folio.org/browse/UIF-157 …
=> UIF-157 Update create current budget

translations/ui-finance/it_IT.json
=> Update translation strings as of 20191220T155503

translations/ui-finance/zh_CN.json
=> Update translation strings as of 20200109T152437

CHANGELOG.md, src/components/FiscalYear/FiscalYearsList/FiscalYearListSearchConfig.js
Search option “All” for fiscal year does not include Code
https://issues.folio.org/browse/UIF-164 …
=> UIF-164 Search option “All” for fiscal year does not include Code

CHANGELOG.md, src/Groups/GroupsList/GroupsListSearchConfig.js
https://issues.folio.org/browse/UIF-163 …
=> UIF-163 Search option “All” for fund groups does not include Code

CHANGELOG.md, src/components/Ledger/LedgerList/LedgerList.js, test/bigtest/tests/funds/FundTags/FundTags-test.js
Default results display on the start page for ledgers (inconsistency with fiscal year/group/fund)
https://issues.folio.org/browse/UIF-160 …
=> UIF-160 Default results display on the start page for ledgers

CHANGELOG.md, package.json
Update settings permission label
https://issues.folio.org/browse/UIF-172
While it's helpful …
=> UIF-172 Update settings permission label

src/common/resources/ledger.js, src/components/Budget/BudgetView/BudgetViewContainer.js, src/components/FiscalYear/FiscalYearDetails/FiscalYearDetailsContainer.js, test/bigtest/tests/budgets/details-budget-test.js, test/bigtest/tests/budgets/edit-budget-test.js
Update Fiscal year record view to display Ledger and related totals for that year
https://issues.folio.org/browse/UIF-149 …
=> UIF-149 display Ledger and related totals for that year

src/components/FiscalYear/FiscalYearsList/FiscalYearListSearchConfig.js
Add `description` to search option 'All' for Fiscal year 
https://issues.folio.org/browse/UIF-164
https://issues.folio.org/browse/UIF-164?focusedCommentId=69012&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-69012
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIF-164 Add description to  search for FY

translations/ui-finance/fr_FR.json
=> Update translation strings as of 20200117T173544

CHANGELOG.md, src/components/Fund/FundBudgets/FundBudgets.js, src/components/Fund/FundBudgets/index.js, src/components/Fund/FundDetails/FundDetailsContainer.js, src/components/Fund/FundLedger/FundLedgerContainer.js, src/components/Fund/FundPlannedBudgets/FundPlannedBudgetsContainer.js, src/components/Fund/FundPlannedBudgets/index.js, src/components/Fund/FundPreviousBudgets/FundPreviousBudgetsContainer.js, src/components/Fund/FundPreviousBudgets/index.js, test/bigtest/tests/budgets/details-budget-test.js, test/bigtest/tests/funds/DeleteFund/DeleteFund-test.js, test/bigtest/tests/funds/FundTags/FundTags-test.js
Not displaying active budgets for fiscal years other than current fiscal year.
https://issues.folio.org/browse/UIF-161
Change loading by budget status to the start date of budget's fiscal year
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> UIF-161 load planned and previous budgets by start date param

src/components/Budget/AddBudgetModal/AddBudgetModal.js, translations/ui-finance/en.json
Show error if no upcoming fiscal year
https://issues.folio.org/browse/UIF-158
While it's …
=> UIF-158 show error in case there is no upcoming  FY

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200127T144839

translations/ui-finance/it_IT.json
=> Update translation strings as of 20200127T201424

CHANGELOG.md, src/components/Ledger/LedgerList/LedgerListSearchConfig.js
Search option “All” for ledger does not include Code
https://issues.folio.org/browse/UIF-165 …
=> UIF-165 Add Code to search option “All” for Ledger

CHANGELOG.md, src/components/Budget/BudgetView/BudgetInformation.js, src/components/Budget/BudgetView/BudgetView.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-162 …
=> UIF-162 Display over encumbered and over expended values on Budget view

CHANGELOG.md, src/FiscalYears/FiscalYearDetails/FiscalYearDetails.js, src/FiscalYears/FiscalYearForm/FiscalYearForm.js, src/Groups/GroupForm/GroupForm.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/components/Budget/BudgetForm/BudgetForm.js, src/components/Budget/BudgetView/BudgetViewContainer.js, src/components/Fund/FundDetails/FundDetailsContainer.js, src/components/Fund/FundForm/FundForm.js, test/bigtest/interactors/budgets/BudgetDetails.js, test/bigtest/interactors/budgets/BudgetEdit.js, test/bigtest/interactors/fiscalYear/FiscalYearForm.js, test/bigtest/interactors/funds/FundForm.js, test/bigtest/interactors/groups/GroupFormInteractor.js, test/bigtest/tests/transactions/addTransfer-test.js
Move record action buttons into "Action" button UX pattern
https://issues.folio.org/browse/UIF-179 …
=> UIF-179 Move action buttons into "Action" button

src/FiscalYears/CreateFiscalYear/CreateFiscalYear.js, src/FiscalYears/EditFiscalYear/EditFiscalYear.js, src/FiscalYears/FiscalYearForm/FiscalYearForm.js, src/FiscalYears/FiscalYearForm/index.js, src/FiscalYears/index.js, src/FiscalYears/utils.js, src/Ledger/CreateLedger/CreateLedger.js, src/Ledger/CreateLedgerFiscalYear/CreateLedgerFiscalYear.js, src/Ledger/CreateLedgerFiscalYear/index.js, src/Ledger/EditLedger/EditLedger.js, src/Ledger/Ledger.js, src/Ledger/LedgerForm/LedgerForm.js, src/Ledger/LedgerList/LedgerListLastMenu.js, test/bigtest/tests/ledgers/CreateLedgerFiscalYear/CreateLedgerCreateFiscalYear-test.js, test/bigtest/tests/ledgers/CreateLedgerFiscalYear/EditLedgerCreateFiscalYear-test.js, test/bigtest/tests/ledgers/LedgerCreate/LedgerCreate-test.js, test/bigtest/tests/ledgers/LedgerEdit/LedgerEdit-test.js
https://issues.folio.org/browse/UIF-176 …
=> UIF-176 - fix create FY from ledger

src/Groups/GroupForm/GroupForm.js
https://issues.folio.org/browse/UIF-178 …
=> UIF-178 fix group from close button

translations/ui-finance/ar.json
=> Update translation strings as of 20200217T172736

translations/ui-finance/fr_FR.json
=> Update translation strings as of 20200220T141728

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200224T151433

src/FiscalYears/FiscalYearsList/FiscalYearsListContainer.js, src/Funds/FundsList/FundsListContainer.js, src/Funds/FundsList/utils.js, src/Groups/GroupsList/GroupsListContainer.js, src/Ledger/LedgerList/LedgerListContainer.js
https://issues.folio.org/browse/UIF-182 …
=> UIF-182 fix ledgers column on funds list

CHANGELOG.md, src/Transactions/TransactionsList/TransactionsFilters/TransactionsFilters.js
https://issues.folio.org/browse/UIF-128 …
=> UIF-128 Filter Finance transaction records by tags

src/index.js
=> use common calout context

src/Transactions/TransactionDetails/TransactionInformation/TransactionInformation.js
switch the order of 'awaiting payment' and 'initial encumbrance'
https://issues.folio.org/browse/UIF-177?focusedCommentId=72057&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-72057 …
=> UIF-177 Change fields order

translations/ui-finance/fr_FR.json
=> Update translation strings as of 20200312T133304

CHANGELOG.md, package.json, src/FiscalYears/FiscalYearDetails/FiscalYearDetailsContainer.js, src/FiscalYears/FiscalYearsList/FiscalYearsListContainer.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundsList/FundsListContainer.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupsList/GroupsListContainer.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/Ledger/LedgerList/LedgerListContainer.js
https://issues.folio.org/browse/UIF-183 …
=> Release v2.0.0

CHANGELOG.md, src/Ledger/LedgerDetails/LedgerGroups.js, src/common/resources/group.js, src/components/ConnectionListing/ConnectionListing.js, test/bigtest/interactors/ledgers/LedgerDetailsInteractor.js, test/bigtest/tests/ledgers/LedgerDetails/LedgerDetails-test.js
https://issues.folio.org/browse/UIF-186 …
=> UIF-186 Ledger groups table not scrolling

src/Groups/CreateGroup/CreateGroup.js
To improve UX, but specific error messages and codes handling will be added later, after Q1 bugfix release
https://issues.folio.org/browse/UIF-188 …
=> UIF-188 WIP show message instead of translation key

src/components/ConnectionListing/ConnectionListing.js
https://issues.folio.org/browse/UIF-186 …
=> UIF-186 fix end of list marker

src/components/ConnectionListing/ConnectionListing.js
to remove extra hor and vert scrolls
https://issues.folio.org/browse/UIF-186
While it's …
=> UIF-186 remove extra scrolls

CHANGELOG.md, src/FiscalYears/FiscalYearDetails/FiscalYearDetailsContainer.js
Fiscal year record displaying all Ledgers
https://issues.folio.org/browse/UIF-190
While it's …
=> UIF-190 Fiscal year record displaying all Ledgers

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200331T152557

src/FiscalYears/FiscalYearDetails/FiscalYearDetailsContainer.js, src/common/resources/fiscalYear.js, test/bigtest/tests/fiscalYear/FiscalYearDetails/FiscalYearDetails-test.js
According to the comment, we should load ledgers not only for the current fiscal year, but even if this year is included in the same series with initial fiscal year of ledger.
https://issues.folio.org/browse/UIF-190 …
=> UIF-190 filter ledgers by fiscal years of the same series

src/components/Budget/AddBudgetModal/AddBudgetModal.js, test/bigtest/tests/funds/CreteCurrentBudget/CreateCurrentBudget-test.js, test/bigtest/tests/funds/CreteCurrentBudget/CreatePlannedBudget-test.js
If there are several fiscal years series there is a change that a wrong one will be preselected for planned budget …
=> UIF-190 fix preselected FY for planned budget

translations/ui-finance/pt_BR.json
=> Update translation strings as of 20200403T124750

CHANGELOG.md, src/Ledger/LedgerDetails/LedgerDetailsContainer.js
On ledger detail view, funds associated with the ledger not in alpha order
https://issues.folio.org/browse/UIF-203 …
=> UIF-203 sort funds

CHANGELOG.md, src/Funds/FundDetails/FundBudgets/FundBudgets.js, src/components/ConnectionListing/ConnectionListing.js
Align actions icons in table to right hand side of view pane(s)
https://issues.folio.org/browse/UINV-138 …
=> UINV-138 show right arrow and align it to the right

.editorconfig, CHANGELOG.md, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/Funds/FundsList/FundsList.js, src/Groups/GroupsList/GroupsList.js, src/Ledger/LedgerList/LedgersList.js, src/Transactions/TransactionsList/TransactionsList.js
is not using the same Expand/Collapse as implemented in Q4 2019
https://issues.folio.org/browse/UIORGS-151 …
=> UIORGS-151 use common icons for collapse/expand filters

CHANGELOG.md, src/components/ConnectionListing/ConnectionListing.js, test/bigtest/interactors/groups/GroupDetailsInteractor.js, test/bigtest/tests/groups/GroupDetails/GroupDetails-test.js
Ability to sort Fund columns on the Group details view
https://issues.folio.org/browse/UIF-204 …
=> UIF-204 Ability to sort Fund columns

package.json
=> Update transactions interface

package.json, src/Transactions/TransactionDetails/TransactionInformation/SourceValue/utils.js
https://issues.folio.org/browse/UIF-184 …
=> UIF-184 Fix invoice-line link

CHANGELOG.md, package.json, src/Transactions/TransactionsList/TransactionsList.js, src/Transactions/TransactionsList/TransactionsListContainer.js
View transactions glitch shows transactions from different budget
https://issues.folio.org/browse/UIF-210 …
=> UIF-210 shows transactions from different budget

CHANGELOG.md, src/Transactions/TransactionsList/TransactionsFilters/TransactionsFilters.js, src/Transactions/TransactionsList/TransactionsList.js, src/Transactions/TransactionsList/TransactionsListContainer.js, src/Transactions/constants.js
Update the sort options for a fund's transaction list
https://issues.folio.org/browse/UIF-202 …
=> UIF-202 Update the sort options for a fund's transaction list

CHANGELOG.md, src/Transactions/BracketizeTransactionAmount/BracketizeTransactionAmount.js, src/Transactions/BracketizeTransactionAmount/index.js, src/Transactions/TransactionsList/TransactionsList.js, src/Transactions/TransactionsList/TransactionsListContainer.js, test/bigtest/interactors/transactions/TransactionsListInteractor.js, test/bigtest/tests/transactions/TransactionsList/TransactionsList-test.js
Display transaction amounts that subtract from the budget in '()' and no negative numbers
https://issues.folio.org/browse/UIF-208
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UIF-208 display sums that decrease budget in brackets

src/Transactions/TransactionsList/TransactionsList.js
fix transaction date column
https://issues.folio.org/browse/UIF-202 …
=> UIF-202 fix sorting of transaction date

src/components/ConnectionListing/ConnectionListing.js
https://issues.folio.org/browse/UIF-205 …
=> UIF-205 fix insesitive case sorting

src/Transactions/TransactionDetails/TransactionDetails.js, src/Transactions/TransactionDetails/TransactionDetailsContainer.js, src/Transactions/TransactionDetails/TransactionInformation/TransactionInformation.js, src/Transactions/TransactionsList/TransactionsList.js
https://issues.folio.org/browse/UIF-208 …
=> UIF-208 display amount the same as in list

CHANGELOG.md, package.json, src/FiscalYears/FiscalYearDetails/FiscalYearDetailsContainer.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundDetails/FundPlannedBudgets/FundPlannedBudgetsContainer.js, src/Funds/FundDetails/FundPreviousBudgets/FundPreviousBudgetsContainer.js, src/Funds/FundForm/FundFormContainer.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Ledger/EditLedger/EditLedger.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/components/Budget/AddBudgetModal/AddBudgetModal.js, src/components/Budget/BudgetForm/BudgetFormContainer.js, src/components/Budget/BudgetView/BudgetViewContainer.js, src/settings/FundTypeSettings/FundTypeSettings.js
https://issues.folio.org/browse/UIF-218 …
=> UIF-218 Update to Stripes v4

CHANGELOG.md, src/components/Budget/AddBudgetModal/AddBudgetModalForm.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-222
Allowable expenditure should be Allowable expenditure percentage
Allowable encumbrance should be Allowable encumbrance percentage
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> UIF-222 Create budget - change field labels

CHANGELOG.md, src/components/Budget/AddBudgetModal/AddBudgetModal.js
https://issues.folio.org/browse/UIF-223
default Allowable expenditure and Allowable encumbrance = 100% …
=> UIF-223 Create budget - allowable default percent

CHANGELOG.md, src/FiscalYears/FiscalYearsList/FiscalYearsListContainer.js, src/Funds/FundsList/FundsListContainer.js, src/Groups/GroupsList/GroupsListContainer.js, src/Ledger/LedgerList/LedgerListContainer.js
Fund and Groups result list "load more" buttons not working properly
https://issues.folio.org/browse/UIF-220 …
=> UIF-220 "load more" buttons not working properly

CHANGELOG.md, src/Funds/FundDetails/FundCurrentBudget/FundCurrentBudgetContainer.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundDetails/FundPlannedBudgets/FundPlannedBudgetsContainer.js, src/Funds/FundDetails/FundPreviousBudgets/FundPreviousBudgetsContainer.js, src/components/Budget/AddBudgetModal/AddBudgetModal.js, src/components/Budget/Budget.js, src/components/Budget/BudgetForm/BudgetFormContainer.js, src/components/Budget/BudgetView/BudgetViewContainer.js, test/bigtest/interactors/budgets/BudgetDetails.js, test/bigtest/tests/budgets/details-budget-test.js, test/bigtest/tests/funds/FundDetails/FundDetails-test.js
https://issues.folio.org/browse/UIF-221 …
=> UIF-221 Fund search should be retained after returning from budget details

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200519T123842

CHANGELOG.md, src/Transactions/TransactionDetails/TransactionInformation/TransactionInformation.js, src/common/const/constants.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-217 …
=> UIF-217 support Pending payment transaction

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200521T142352

translations/ui-finance/ar.json, translations/ui-finance/ru.json
=> Update translation strings as of 20200522T132417

translations/ui-finance/fr_FR.json, translations/ui-finance/pt_BR.json
=> Update translation strings as of 20200526T141248

src/FiscalYears/FiscalYearDetails/FiscalYearDetailsContainer.js, src/FiscalYears/utils.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundForm/FundFormContainer.js, src/Groups/CreateGroup/CreateGroup.js, src/Groups/EditGroup/EditGroup.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Ledger/CreateLedger/CreateLedger.js, src/Ledger/EditLedger/EditLedger.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/components/Budget/AddBudgetModal/AddBudgetModal.js, src/components/Budget/BudgetView/BudgetViewContainer.js
=> UIOR-567 fix missing callouts

translations/ui-finance/en.json
=> fix translation

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200604T202430

translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200608T134746

package.json, src/Funds/FundDetails/FundPlannedBudgets/FundPlannedBudgetsContainer.js, src/Funds/FundDetails/FundPreviousBudgets/FundPreviousBudgetsContainer.js, src/Groups/GroupDetails/utils.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, test/bigtest/interactors/common/tags/TagsPane.js, test/bigtest/tests/funds/FundTags/FundTags-test.js
=> fix limit max

src/Funds/FundDetails/FundBudgets/FundBudgets.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundDetails/FundPlannedBudgets/FundPlannedBudgetsContainer.js, src/Funds/FundDetails/FundPreviousBudgets/FundPreviousBudgetsContainer.js, src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupInformation/GroupInformation.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/components/Budget/BudgetView/BudgetInformation.js, src/components/Budget/BudgetView/BudgetSummary.js, src/components/Budget/BudgetView/BudgetView.js, src/components/Budget/BudgetView/BudgetViewContainer.js, src/components/ConnectionListing/ConnectionListing.js
https://issues.folio.org/browse/UIF-226 …
=> UIF-226 use fiscal year currency

src/Funds/FundDetails/FundPlannedBudgets/FundPlannedBudgetsContainer.js, test/bigtest/network/factories/fiscalYear.js
=> UIF-226 fi planned budgets query

CHANGELOG.md, package.json, test/bigtest/interactors/common/tags/TagsPane.js, translations/ui-finance/en.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json
* fixed missing translation;
* fixed tests on build artifacts; …
=> Release v2.1.1

translations/ui-finance/ru.json
=> Update translation strings as of 20200618T161121

CHANGELOG.md, src/FiscalYears/FiscalYearDetails/FiscalYearDetails.js
https://issues.folio.org/browse/UIF-231 …
=> UIF-231 Fiscal year Allocated total is calculated incorrectly

CHANGELOG.md, package.json
=> UISACQCOMP-3

CHANGELOG.md, package.json
=> Release v2.1.2 (#363)

src/FiscalYears/FiscalYears.js, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/Funds/Funds.js, src/Funds/FundsList/FundsList.js, src/Groups/Groups.js, src/Groups/GroupsList/GroupsList.js, src/Ledger/Ledger.js, src/Ledger/LedgerList/LedgersList.js, src/Transactions/Transactions.js, src/Transactions/TransactionsList/TransactionsList.js, src/common/CheckPermission/CheckPermission.js, src/common/CheckPermission/index.js, src/common/NoPermissionsMessage/NoPermissionsMessage.js, src/common/NoPermissionsMessage/index.js, src/components/Budget/Budget.js, src/components/Main/Main.js, src/components/Main/utils.js, translations/ui-finance/en.json
Improve permissions
- show `<NoPermissionsMessage>` instead of blank pane or list
- check permissions for initial route …
=> UIF-228 Add no permissions message

translations/ui-finance/fr_FR.json, translations/ui-finance/pt_BR.json, translations/ui-finance/ru.json
=> Update translation strings as of 20200707T213422

CHANGELOG.md, src/Transactions/TransactionsList/TransactionsList.js
https://issues.folio.org/browse/UIF-229
cursor to not change on hovering column headers that aren't sortable
so that it is clear which columns can be sorted and which ones can't
Use `nonInteractiveHeaders` prop for MCL …
=> UIF-229 change mouse cursor for non-sortable columns

CHANGELOG.md, package.json, src/common/const/api.js, src/settings/ExpenseTypeSettings/ExpenseTypeSettings.js, src/settings/ExpenseTypeSettings/index.js, src/settings/FinanceSettings.js, test/bigtest/interactors/settings/ExpenseTypeSettingsInteractor.js, test/bigtest/network/config.js, test/bigtest/network/configs/expenseClasses.js, test/bigtest/network/factories/expenseClass.js, test/bigtest/network/models/expenseClass.js, test/bigtest/network/serializers/expenseClass.js, test/bigtest/tests/settings/expenseTypes/ExpenseTypeSettings-test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-211 …
=> UIF-211 CRUD expense classes in Finance settings

translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-228?focusedCommentId=82780&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-82780 …
=> UIF-228 Fix translation

src/Funds/FundsList/FundsListFilters/FundsListFilters.js
- add id for `<SelectionFilter>` as required prop …
=> Fix console warnings

translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json
=> Update translation strings as of 20200722T015055

CHANGELOG.md, src/Ledger/LedgerForm/LedgerForm.js
https://issues.folio.org/browse/UIF-193
- add `Ledger information` accordion
- add `pristine` prop to `<FormFooter>` as required prop …
=> UIF-193 Edit ledger - Certain ARIA roles must be contained by particular parents

translations/ui-finance/pt_BR.json
=> Update translation strings as of 20200723T031126

CHANGELOG.md, src/FiscalYears/FiscalYearForm/FiscalYearForm.js
https://issues.folio.org/browse/UIF-196 …
=> UIF-196 Edit fiscal year - Certain ARIA roles must be contained by particular parents

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200727T130814

package.json
=> UIF-228 Update permissions display name

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200804T124827

src/common/ExpenseClasses/ExpenseClasses.js, src/components/Budget/BudgetView/BudgetView.js
Pass fiscalYear currency to budget expense classes …
=> UIF-214 Add currency

CHANGELOG.md, src/Funds/FundDetails/FundBudgets/FundBudgets.js, src/components/Budget/BudgetView/BudgetSummary.js, src/components/ConnectionListing/ConnectionListing.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-215 …
=> UIF-215 Display Net transfers amount on budget

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200806T130626

src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupExpenseClasses/GroupExpenseClasses.js, test/bigtest/network/configs/groups.js
https://issues.folio.org/browse/UIF-227 …
=> UIF-227 back-end integration

translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200807T145751

CHANGELOG.md, src/components/Budget/BudgetView/BudgetViewContainer.js
https://issues.folio.org/browse/UIF-185 …
=> UIF-185 New icons for Allocate and Transfer

translations/ui-finance/fr_FR.json, translations/ui-finance/pt_BR.json
=> Update translation strings as of 20200811T193833

translations/ui-finance/it_IT.json
=> Update translation strings as of 20200813T135432

src/Groups/GroupDetails/GroupExpenseClasses/GroupExpenseClasses.js, test/bigtest/network/configs/groups.js, test/bigtest/network/factories/groupExpenseClassTotal.js, test/bigtest/network/models/groupExpenseClassTotal.js, test/bigtest/network/serializers/groupExpenseClassTotal.js, test/bigtest/tests/groups/GroupDetails/GroupDetails-test.js
https://issues.folio.org/browse/UIF-227 …
=> UIF-227 integrate back-end

CHANGELOG.md, src/FiscalYears/FiscalYearForm/FiscalYearForm.js, src/Funds/FundForm/FundForm.js, src/Groups/GroupForm/GroupForm.js, src/Ledger/LedgerForm/LedgerForm.js
https://issues.folio.org/browse/UIF-197 …
=> UIF-197 fix form labels a11y issue

CHANGELOG.md, src/components/Budget/BudgetView/BudgetInformation.js, test/bigtest/interactors/common/tags/TagsPane.js
Allowable expenditure/encumbrance display as 0% when not set
https://issues.folio.org/browse/UIF-240 …
=> UIF-240 display NoValue if not set

translations/ui-finance/fr_FR.json, translations/ui-finance/it_IT.json
=> Update translation strings as of 20200824T140725

package.json, src/components/ConnectionListing/ConnectionListing.js
https://issues.folio.org/browse/UINV-178 …
=> UINV-178 use FrontendSortingMCL

translations/ui-finance/ar.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20200901T173106

CHANGELOG.md, src/Ledger/CreateLedger/CreateLedger.js, src/Ledger/EditLedger/EditLedger.js, src/Ledger/LedgerForm/LedgerForm.js, src/Ledger/constants.js, src/common/FiscalYearField/FiscalYearField.js, src/components/Budget/AddBudgetModal/AddBudgetModalForm.js, src/components/Budget/constants.js
https://issues.folio.org/browse/UIF-247
https://issues.folio.org/browse/UIF-249
While it's …
=> UIF-247 UIF-249 Migrate budget and ledger forms to react-final-form

CHANGELOG.md, src/Groups/CreateGroup/CreateGroup.js, src/Groups/EditGroup/EditGroup.js, src/Groups/GroupForm/GroupForm.js
https://issues.folio.org/browse/UIF-248 …
=> UIF-248 Migrate Group form to react-final-form

CHANGELOG.md, src/Transactions/CreateTransaction/CreateTransactionModal.js, src/common/utils/fundValidation.js
https://issues.folio.org/browse/UIF-250 …
=> UIF-250 Migrate Transaction form to RFF

CHANGELOG.md, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-244 …
=> UIF-244 Display error message when attempting delete a Budget with Expense Classes

src/Funds/FundGroups/ViewFundGroups/ViewFundGroups.js, src/Funds/FundGroups/ViewFundGroups/ViewFundGroupsContainer.js
=> UIF-251 missed no groups selected for fund

src/Funds/FundDetails/FundPreviousBudgets/FundPreviousBudgetsContainer.js
=> fix wrong previous budget

translations/ui-finance/zh_CN.json
=> Update translation strings as of 20200928T202231

CHANGELOG.md, src/Funds/FundDetails/FundExpenseClasses/FundExpenseClasses.js, src/common/ExpenseClasses/ExpenseClasses.js
Fund view - Display encumbered and awaiting payment amount in "Current expense classes" table
https://issues.folio.org/browse/UIF-258 …
=> UIF-258 display more fields at Fund Details

src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/Transactions/constants.js, src/common/const/constants.js, src/components/Budget/BudgetView/BudgetViewContainer.js, test/bigtest/tests/transactions/TransactionDetails/TransactionDetailsEncumbranceType-test.js
=> Use common transaction types

translations/ui-finance/ja.json
=> Update translation strings as of 20201007T133333

translations/ui-finance/ja.json
=> Update translation strings as of 20201030T134930

CHANGELOG.md, src/Groups/GroupDetails/GroupExpenseClasses/GroupExpenseClasses.js
https://issues.folio.org/browse/UIF-259 …
=> UIF-259 show more fields at group level

CHANGELOG.md, package.json
just missing permission
https://issues.folio.org/browse/UIF-265 …
=> UIF-265 missed permission

CHANGELOG.md, src/Ledger/LedgerForm/FieldLedgerName/FieldLedgerName.js, src/Ledger/LedgerForm/FieldLedgerName/index.js, src/Ledger/LedgerForm/LedgerForm.js, src/Ledger/LedgerForm/validateLedger.test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-256 …
=> UIF-256 Error message: Ledger name already in use

translations/ui-finance/ar.json, translations/ui-finance/ber.json, translations/ui-finance/ca.json, translations/ui-finance/da.json, translations/ui-finance/de.json, translations/ui-finance/en_GB.json, translations/ui-finance/en_SE.json, translations/ui-finance/en_US.json, translations/ui-finance/es.json, translations/ui-finance/es_419.json, translations/ui-finance/es_ES.json, translations/ui-finance/fr.json, translations/ui-finance/fr_FR.json, translations/ui-finance/he.json, translations/ui-finance/hi_IN.json, translations/ui-finance/hu.json, translations/ui-finance/it_IT.json, translations/ui-finance/ja.json, translations/ui-finance/ko.json, translations/ui-finance/pl.json, translations/ui-finance/pt_BR.json, translations/ui-finance/pt_PT.json, translations/ui-finance/ru.json, translations/ui-finance/ur.json, translations/ui-finance/zh_CN.json, translations/ui-finance/zh_TW.json
=> Update translation strings as of 20201124T212804

CHANGELOG.md, package.json, src/Ledger/LedgerDetails/LedgerDetails.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, test/bigtest/interactors/ledgers/LedgerDetailsInteractor.js, test/bigtest/tests/ledgers/LedgerDetails/LedgerDetails-test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-168 …
=> UIF-168 button Rollover

src/Ledger/Ledger.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/Ledger/RolloverLedger/RolloverLedger.js, src/Ledger/RolloverLedger/RolloverLedgerBudgets.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, src/Ledger/RolloverLedger/index.js, test/bigtest/interactors/ledgers/LedgerRolloverInteractor.js, test/bigtest/tests/ledgers/LedgerDetails/LedgerDetails-test.js, translations/ui-finance/en.json
Initial commit for rollover form to unblock other related tickets
https://issues.folio.org/browse/UIF-169 …
=> UIF-169 rollover form skeleton

src/Ledger/Ledger.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/common/const/routes.js, test/bigtest/tests/ledgers/LedgerCreate/LedgerCreate-test.js
https://issues.folio.org/browse/UIF-168 …
=> UIF-168 new icon

CHANGELOG.md, src/Ledger/Ledger.js, src/Ledger/RolloverLedger/RolloverFiscalYears.js, src/Ledger/RolloverLedger/RolloverLedger.js, src/Ledger/RolloverLedger/RolloverLedger.test.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, src/Ledger/RolloverLedgerCreateFiscalYear/RolloverLedgerCreateFiscalYear.js, src/Ledger/RolloverLedgerCreateFiscalYear/index.js, translations/ui-finance/en.json
Set Fiscal year detail during fiscal year rollover
https://issues.folio.org/browse/UIF-254 …
=> UIF-254 Set Fiscal year detail during rollover

src/Ledger/RolloverLedger/RolloverLedgerEncumbrances.js
https://issues.folio.org/browse/UIF-170 …
=> UIF-170 disable fields that are not in rollover

CHANGELOG.md, src/FiscalYears/CreateFiscalYear/CreateFiscalYear.js, src/FiscalYears/utils.js, src/Ledger/CreateLedgerFiscalYear/CreateLedgerFiscalYear.js, src/Ledger/RolloverLedger/RolloverFiscalYears.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, src/Ledger/RolloverLedgerCreateFiscalYear/RolloverLedgerCreateFiscalYear.js, src/common/FiscalYearField/FiscalYearFieldContainer.js, src/common/resources/fiscalYear.js, test/bigtest/network/factories/fiscalYear.js, translations/ui-finance/en.json
* Close all current budgets when executing fiscal year rollover
* fix selecting fiscal year of another series
https://issues.folio.org/browse/UIF-175 …
=> UIF-175 Close all current budgets when rollover

src/Ledger/RolloverLedger/RolloverFiscalYears.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.js
https://issues.folio.org/browse/UIF-175 …
=> UIF-175 add margin for checkbox

CHANGELOG.md, PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/UIF-272 …
=> UIF-272  Add personal data disclosure form

CHANGELOG.md, src/Ledger/RolloverLedger/RolloverLedgerEncumbrances.js
https://issues.folio.org/browse/UIF-274 …
=> UIF-274 fix required for disabled 'based on'

CHANGELOG.md, package.json, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/Ledger/LedgerDetails/LedgerRolloverProgress/LedgerRolloverProgress.js, src/Ledger/LedgerDetails/useRolloverProgressPolling.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, src/common/const/constants.js, src/common/resources/ledger.js
* Execute fiscal year rollover
* fix some issues with displaying progress bar.
https://issues.folio.org/browse/UIF-171 …
=> UIF-171 start process with stub data

src/Ledger/RolloverLedger/RolloverLedgerContainer.js, translations/ui-finance/en.json
Execute fiscal year rollover
https://issues.folio.org/browse/UIF-171 …
=> UIF-171 remove stub data

src/Ledger/RolloverLedger/RolloverField.js, src/Ledger/RolloverLedger/RolloverLedgerEncumbrances.js
fix comment in https://issues.folio.org/browse/UIF-274
While it's helpful for reviewers to …
=> UIF-274 clear fields if checkbox unchecked

package.json, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/Ledger/LedgerDetails/LedgerRolloverProgress/LedgerRolloverProgress.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, translations/ui-finance/en.json
show close btn and add missing permissions
https://issues.folio.org/browse/UIF-171
While …
=> UIF-171 handle finished progress and close btn

src/common/FinancialSummary/FinancialSummary.js
https://issues.folio.org/browse/UIF-261?focusedCommentId=95338&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-95338 …
=> UIF-261 - fix spaces

src/Ledger/LedgerDetails/RolloverErrorsLink/RolloverErrorsLink.js, translations/ui-finance/en.json, translations/ui-finance/en_US.json
comment in https://issues.folio.org/browse/UIF-238 …
=> UIF-238 change close btn label

src/FiscalYears/FiscalYearDetails/FiscalYearDetails.js, src/common/FinancialSummary/FinancialSummary.js, src/common/FinancialSummary/FundingInformation/FundingInformation.js, src/common/FinancialSummary/utils.js
https://issues.folio.org/browse/UIF-262?focusedCommentId=95617&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-95617
- hide `allocationTo`, `allocationFrom`, `netTransfers` amounts for FY …
=> UIF-262 Hide amounts for FY

CHANGELOG.md, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-279 …
=> UIF-279 rollover confirmation message

src/Ledger/RolloverLedger/RolloverLedgerContainer.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-238 …
=> UIF-238 fix confirm btn label

package.json
there are no such permission on the back-end, so we need to include granular permissions …
=> UIF-171 fix perissions

CHANGELOG.md, src/Ledger/RolloverLedger/RolloverLedgerBudgets.js, src/Ledger/RolloverLedger/SetAllowancesField.js, translations/ui-finance/en.json
Allow user to intentionally reset budget allowances during rollover
https://issues.folio.org/browse/UIF-275 …
=> UIF-275 new setAllowances field on rollover

src/Transactions/TransactionDetails/TransactionDetails.js, src/common/const/constants.js
review fixes from the ticket, fix permission to check specific UI, show btn when encumbrance is not released
https://issues.folio.org/browse/UIF-271 …
=> UIF-271 review fixes of permission and btn visibility

CHANGELOG.md, translations/ui-finance/en.json
add label
https://issues.folio.org/browse/UIF-282 …
=> UIF-282 fix label for Rollover transaction

src/Transactions/TransactionDetails/TransactionDetailsContainer.js
=> UIF-271 refresh transaction after release

CHANGELOG.md, src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/Transactions/CreateTransaction/CreateTransactionModal.js, src/common/utils/fundValidation.js, translations/ui-finance/en.json
Allow only positive allocation to or from budget - Update field validation
https://issues.folio.org/browse/UIF-280 …
=> UIF-280 fix valdiation on create Allocation

package.json
https://issues.folio.org/browse/UIF-287 …
=> UIF-287 Update stripes-cli to v2

src/Ledger/RolloverLedger/useRolloverFiscalYears.test.js
=> UIF-286 fix test

src/Transactions/TransactionDetails/TransactionInformation/SourceValue/useSourceLink.js
https://issues.folio.org/browse/UIF-283?focusedCommentId=98269&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-98269 …
=> UIF-283 Display vendor invoice number

CHANGELOG.md, package.json, src/settings/ExpenseClassSettings/ExpenseClassHelper.js, src/settings/ExpenseClassSettings/ExpenseClassSettings.css, src/settings/ExpenseClassSettings/ExpenseClassSettings.js, src/settings/ExpenseClassSettings/ExpenseClassSettings.test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-291 …
=> UIF-291 Add help text to expense classes in settings area

translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-291 …
=> UIF-291 fix expense classes help text

translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-300 …
=> UIF-300 Typo in Expense class "Awaiting payment" column header

src/Transactions/TransactionsList/TransactionsList.js
https://issues.folio.org/browse/UIF-301 …
=> UIF-301 Transactions filters pane resize not working

CHANGELOG.md, src/FiscalYears/FiscalYearDetails/FiscalYearDetails.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Groups/GroupDetails/GroupDetails.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/common/DetailsActions/DetailsEditAction/DetailsEditAction.js
https://issues.folio.org/browse/UIF-295 …
=> UIF-295 Acquisition units no longer restrict edit create or delete actions from action menu

src/FiscalYears/FiscalYearDetails/FiscalYearDetailsContainer.js, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundsList/FundsList.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupsList/GroupsList.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/Ledger/LedgerList/LedgersList.js, src/Transactions/TransactionDetails/TransactionDetailsContainer.js, src/Transactions/TransactionsList/TransactionsList.js, test/bigtest/tests/ledgers/LedgerDetails/LedgerDetails-test.js
https://issues.folio.org/browse/UIF-299 …
=> UIF-299 Resizable Panes - Persistence

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIF-302 …
=> UIF-302 v2.3.3 release

package.json, src/index.js
=> lock broken dep

src/FiscalYears/FiscalYearDetails/FiscalYearDetails.js, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundsList/FundsList.js, src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupsList/GroupsList.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/Ledger/LedgerList/LedgersList.js, src/components/Budget/BudgetView/BudgetViewContainer.js
=> UIF-293 Shortcut keys: check permissions

CHANGELOG.md, src/components/Main/Main.js, src/index.js, test/bigtest/tests/transactions/TransactionDetails/TransactionDetailsEncumbranceType-test.js
https://issues.folio.org/browse/UIF-305 …
=> UIF-305 Implement Keyboard shortcuts modal

src/FiscalYears/FiscalYearDetails/FiscalYearDetails.js, src/FiscalYears/FiscalYearForm/FiscalYearForm.js, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundForm/FundForm.js, src/Funds/FundsList/FundsList.js, src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupForm/GroupForm.js, src/Groups/GroupsList/GroupsList.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/Ledger/LedgerForm/LedgerForm.js, src/Ledger/LedgerList/LedgersList.js, src/components/Budget/BudgetForm/BudgetForm.js, src/components/Budget/BudgetView/BudgetViewContainer.js, src/index.js
=> use common andleKeyCommand

CHANGELOG.md, Jenkinsfile, package.json
https://issues.folio.org/browse/UIF-298 …
=> UIF-298 Compile Translation Files into AST

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIF-307 …
=> UIF-307 Update package.json

CHANGELOG.md, src/Ledger/LedgerDetails/LedgerGroups.js
https://issues.folio.org/browse/UIF-309 …
=> UIF-309 Fix fetching ledger groups

CHANGELOG.md, src/components/Budget/BudgetView/BudgetInformation.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-311 …
=> UIF-311 Cannot edit budget 'actions required' field

CHANGELOG.md, src/components/Budget/BudgetForm/BudgetInformationFields.js, src/components/Budget/BudgetView/BudgetInformation.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-312 …
=> UIF-312 Should not display budget 'allocation date' field as it is NOT in the schema

CHANGELOG.md, src/Transactions/CreateTransaction/CreateTransactionModal.js, src/Transactions/CreateTransaction/CreateTransactionModal.test.js
https://issues.folio.org/browse/UIF-314 …
=> UIF-314 Cannot allocate or transfer cents

CHANGELOG.md, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-318 …
=> UIF-318 FY is successfully saved with wrong date

src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/Transactions/CreateTransaction/CreateTransactionContainer.test.js, src/Transactions/CreateTransaction/CreateTransactionModal.js, src/Transactions/CreateTransaction/CreateTransactionModal.test.js, src/Transactions/constants.js, src/components/Budget/BudgetView/BudgetViewContainer.js, src/components/Budget/BudgetView/BudgetViewContainer.test.js, test/bigtest/interactors/budgets/BudgetDetails.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-317 …
=> UIF-317 Simplify UX for creating allocations

CHANGELOG.md, package.json, src/common/const/api.js, src/settings/ExportFundSettings/ExportFundSettings.css, src/settings/ExportFundSettings/ExportFundSettings.js, src/settings/ExportFundSettings/ExportFundSettings.test.js, src/settings/ExportFundSettings/constants.js, src/settings/ExportFundSettings/index.js, src/settings/ExportFundSettings/useExportFund.js, src/settings/ExportFundSettings/useExportFund.test.js, src/settings/ExportFundSettings/useFiscalYearOptions.js, src/settings/ExportFundSettings/useFiscalYearOptions.test.js, src/settings/ExportFundSettings/utils.js, src/settings/FinanceSettings.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-320 …
=> UIF-320 Export combined Fund code list

src/settings/ExportFundSettings/ExportFundSettings.js
=> UIF-320 Reset FY after export

CHANGELOG.md, src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/Transactions/CreateTransaction/CreateTransactionModal.js, src/Transactions/CreateTransaction/CreateTransactionModal.test.js
https://issues.folio.org/browse/UIF-322 …
=> UIF-322 Add fund code as an option for allocation/transfer

CHANGELOG.md, src/Funds/FundForm/FundForm.js, src/Funds/FundForm/FundForm.test.js, src/common/utils/validateDuplicateFieldValue.js, src/common/utils/validateDuplicateFieldValue.test.js, src/settings/ExpenseClassSettings/ExpenseClassSettings.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-323 …
=> UIF-323 Add validation for Fund and Exp class code

package.json, test/bigtest/tests/ledgers/LedgerCreate/LedgerCreate-test.js, test/bigtest/tests/ledgers/LedgerDetails/LedgerDetails-test.js
=> bump up "finance.expense-classes" interface

CHANGELOG.md, src/Groups/GroupsList/GroupsList.js, src/Groups/GroupsList/GroupsList.test.js, src/Groups/GroupsList/GroupsListContainer.js, src/Groups/GroupsList/GroupsListContainer.test.js, src/Groups/GroupsList/hooks/index.js, src/Groups/GroupsList/hooks/useBuildQuery/index.js, src/Groups/GroupsList/hooks/useBuildQuery/useBuildQuery.js, src/Groups/GroupsList/hooks/useBuildQuery/useBuildQuery.test.js, src/Groups/GroupsList/hooks/useGroups/index.js, src/Groups/GroupsList/hooks/useGroups/useGroups.js, src/Groups/GroupsList/hooks/useGroups/useGroups.test.js, src/Groups/GroupsList/index.js, test/bigtest/network/factories/budget.js, test/bigtest/network/factories/budgetExpenseClassTotal.js, test/bigtest/network/factories/fiscalYear.js, test/bigtest/network/factories/fundType.js, test/bigtest/network/factories/group.js, test/bigtest/network/factories/groupExpenseClassTotal.js, test/bigtest/network/factories/groupFundFiscalYear.js, test/bigtest/network/factories/groupSummary.js, test/bigtest/network/factories/ledger.js, test/bigtest/tests/groups/GroupCreate/GroupCreate-test.js, test/bigtest/tests/groups/GroupEdit/GroupEdit-test.js, test/bigtest/tests/groups/GroupsList/GroupsList-test.js
https://issues.folio.org/browse/UIF-326 …
=> UIF-326 Groups - MCL Next/Previous pagination

CHANGELOG.md, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/FiscalYears/FiscalYearsList/FiscalYearsList.test.js, src/FiscalYears/FiscalYearsList/FiscalYearsListContainer.js, src/FiscalYears/FiscalYearsList/FiscalYearsListContainer.test.js, src/FiscalYears/FiscalYearsList/hooks/index.js, src/FiscalYears/FiscalYearsList/hooks/useBuildQuery/index.js, src/FiscalYears/FiscalYearsList/hooks/useBuildQuery/useBuildQuery.js, src/FiscalYears/FiscalYearsList/hooks/useBuildQuery/useBuildQuery.test.js, src/FiscalYears/FiscalYearsList/hooks/useFiscalYears/index.js, src/FiscalYears/FiscalYearsList/hooks/useFiscalYears/useFiscalYears.js, src/FiscalYears/FiscalYearsList/hooks/useFiscalYears/useFiscalYears.test.js, src/FiscalYears/FiscalYearsList/index.js, test/bigtest/tests/fiscalYear/CreateFiscalYear/CreateFiscalYear-test.js, test/bigtest/tests/fiscalYear/FiscalYearEdit/FiscalYearEdit-test.js, test/bigtest/tests/fiscalYear/FiscalYearList/FiscalYearList-test.js, test/bigtest/tests/funds/FundsList/FundsList-test.js
https://issues.folio.org/browse/UIF-328 …
=> UIF-328 Fiscal years Next/Previous pagination

CHANGELOG.md, src/Funds/FundsList/FundsList.js, src/Funds/FundsList/FundsList.test.js, src/Funds/FundsList/FundsListContainer.js, src/Funds/FundsList/FundsListContainer.test.js, src/Funds/FundsList/hooks/index.js, src/Funds/FundsList/hooks/useFunds/index.js, src/Funds/FundsList/hooks/useFunds/useFunds.js, src/Funds/FundsList/hooks/useFunds/useFunds.test.js, test/bigtest/tests/funds/CreateFund/CreateFund-test.js, test/bigtest/tests/funds/FundsList/FundsList-test.js
https://issues.folio.org/browse/UIF-325 …
=> UIF-325 Funds - Implement MCL Next/Previous pagination

CHANGELOG.md, src/Ledger/LedgerList/LedgerListContainer.js, src/Ledger/LedgerList/LedgerListContainer.test.js, src/Ledger/LedgerList/LedgersList.js, src/Ledger/LedgerList/LedgersList.test.js, src/Ledger/LedgerList/hooks/index.js, src/Ledger/LedgerList/hooks/useLedgers/index.js, src/Ledger/LedgerList/hooks/useLedgers/useLedgers.js, src/Ledger/LedgerList/hooks/useLedgers/useLedgers.test.js, test/bigtest/tests/funds/FundsList/FundsList-test.js, test/bigtest/tests/ledgers/LedgersList/LedgersList-test.js
https://issues.folio.org/browse/UIF-327 …
=> UIF-327 Ledgers Tab - Implement MCL Next/Previous pagination

CHANGELOG.md, src/FiscalYears/FiscalYearsList/FiscalYearsListFilter/FiscalYearsListFilter.js, src/FiscalYears/FiscalYearsList/FiscalYearsListFilter/FiscalYearsListFilter.test.js, src/Funds/FundsList/FundsListFilters/FundsListFilters.js, src/Funds/FundsList/FundsListFilters/FundsListFilters.test.js, src/Groups/GroupsList/GroupsListFilters/GroupsListFilters.js, src/Groups/GroupsList/GroupsListFilters/GroupsListFilters.test.js, src/Ledger/LedgerList/LedgerListFilters/LedgerListFilters.js, src/Ledger/LedgerList/LedgerListFilters/LedgerListFilters.test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-331 …
=> UIF-331 Filter label contains extra 's'

CHANGELOG.md, src/Transactions/TransactionsList/TransactionsList.js, src/Transactions/TransactionsList/TransactionsList.test.js, src/Transactions/TransactionsList/TransactionsListContainer.js, src/Transactions/TransactionsList/TransactionsListContainer.test.js, src/Transactions/TransactionsList/hooks/index.js, src/Transactions/TransactionsList/hooks/useBudget/index.js, src/Transactions/TransactionsList/hooks/useBudget/useBudget.js, src/Transactions/TransactionsList/hooks/useBuildQuery/index.js, src/Transactions/TransactionsList/hooks/useBuildQuery/useBuildQuery.js, src/Transactions/TransactionsList/hooks/useBuildQuery/useBuildQuery.test.js, src/Transactions/TransactionsList/hooks/useTransactions/index.js, src/Transactions/TransactionsList/hooks/useTransactions/useTransactions.js, src/Transactions/TransactionsList/hooks/useTransactions/useTransactions.test.js
https://issues.folio.org/browse/UIF-342 …
=> UIF-342 Transactions - Implement MCL Next/Previous pagination

CHANGELOG.md, package.json, src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupDetails/GroupDetailsContainer.test.js, src/Groups/GroupDetails/hooks/index.js, src/Groups/GroupDetails/hooks/useFundGroupMutation/index.js, src/Groups/GroupDetails/hooks/useFundGroupMutation/useFundGroupMutation.js, src/Groups/GroupDetails/hooks/useFundsGroupMutation/index.js, src/Groups/GroupDetails/hooks/useFundsGroupMutation/useFundsGroupMutation.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-339
tests for hooks will be added in separate PR
While …
=> UIF-339 Allow user to add multiple funds to a group from group view

CHANGELOG.md, src/Groups/GroupDetails/GroupDetailsContainer.js
https://issues.folio.org/browse/UIF-345 …
=> UIF-345 Fiscal year is empty after adding funds to new group

CHANGELOG.md, src/Ledger/constants.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-324 …
=> UIF-324 Allow user to base encumbrance on "Initial encumbrance" during rollover

package.json
=> Bump up interfaces

src/Ledger/constants.js
=> UIF-324 Initial Amount

CHANGELOG.md, package.json, src/Ledger/LedgerDetails/LedgerInformation.js, src/Ledger/LedgerForm/LedgerForm.js, test/bigtest/tests/budgets/delete-budget-test.js, test/bigtest/tests/funds/FundTags/FundTags-test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-349 …
=> UIF-349 Edit restrictExpenditures, restrictEncumbrance ledger toggles

src/Ledger/CreateLedger/CreateLedger.js
https://issues.folio.org/browse/UIF-349 …
=> UIF-349 restrictEncumbrance and restrictExpenditures are initialized as true on BE when undefined is passed

CHANGELOG.md, src/Transactions/BracketizeTransactionAmount/BracketizeTransactionAmount.css, src/Transactions/BracketizeTransactionAmount/BracketizeTransactionAmount.js, src/Transactions/BracketizeTransactionAmount/BracketizeTransactionAmount.test.js, src/Transactions/TransactionDetails/TransactionInformation/TransactionInformation.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-316 …
=> UIF-316 Display transactions as Voided for canceled invoices

CHANGELOG.md, src/settings/ExportFundSettings/ExportFundSettings.js
https://issues.folio.org/browse/UIF-354 …
=> UIF-354 Settings > Finance > change focus

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIF-333 …
=> UIF-333 Refactor psets away from backend ".all"

CHANGELOG.md, src/Transactions/BracketizeTransactionAmount/BracketizeTransactionAmount.js
https://issues.folio.org/browse/UINV-358 …
=> UINV-358 Voided amount not displayed for voided transactions

CHANGELOG.md, src/FiscalYears/FiscalYearDetails/FiscalYearDetails.js, src/FiscalYears/FiscalYearDetails/FiscalYearGroups/FiscalYearGroups.js, src/Funds/FundDetails/FundBudgets/FundBudgets.js, src/Ledger/LedgerDetails/LedgerGroups.js, src/Ledger/RolloverLedger/RolloverField.js, src/Ledger/RolloverLedger/RolloverLedgerBudgets.js, src/Ledger/RolloverLedger/RolloverLedgerEncumbrances.js, src/Ledger/RolloverLedger/SetAllowancesField.js, src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/Transactions/CreateTransaction/CreateTransactionModal.js, src/common/FinanceNavigation/FinanceNavigation.js, src/common/FinanceNavigation/constants.js, src/common/FinancialSummary/FinancialActivity/FinancialActivity.js, src/common/FinancialSummary/FundingInformation/FundingInformation.js, src/common/FinancialSummary/Overages/Overages.js, src/common/RelatedFunds/RelatedFunds.js, src/components/Budget/AddBudgetModal/AddBudgetModal.js, src/components/Budget/AddBudgetModal/AddBudgetModalForm.js, src/components/ConnectionListing/ConnectionListing.js
https://issues.folio.org/browse/UIF-361 …
=> UIF-361 - Accessibility analysis

CHANGELOG.md, src/Ledger/LedgerDetails/RolloverErrorsLink/RolloverErrorsLink.js, src/settings/ExportFundSettings/utils.js
https://issues.folio.org/browse/UIF-364 …
=> UIF-364 exportCsv is deprecated in stripes-utils

CHANGELOG.md, src/Funds/FundDetails/FundBudgets/FundBudgets.js, src/Funds/FundDetails/FundCurrentBudget/FundCurrentBudgetContainer.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundDetails/FundDetailsContainer.test.js, src/Funds/FundDetails/FundPlannedBudgets/FundPlannedBudgetsContainer.js, src/Funds/hooks/index.js, src/Funds/hooks/useBudgetsFiscalYears/index.js, src/Funds/hooks/useBudgetsFiscalYears/useBudgetsFiscalYears.js, src/Funds/hooks/useBudgetsFiscalYears/useBudgetsFiscalYears.test.js, src/Funds/utils/getPlannedFiscalYears.js, src/Funds/utils/getPlannedFiscalYears.test.js, src/Funds/utils/index.js, src/common/FiscalYearField/FiscalYearFieldContainer.js, src/components/Budget/AddBudgetModal/AddBudgetModal.js, src/components/Budget/AddBudgetModal/AddBudgetModal.test.js, src/components/Budget/AddBudgetModal/AddBudgetModalForm.js
https://issues.folio.org/browse/UIF-359 …
=> UIF-359 Allow user to create multiple planned budgets

CHANGELOG.md, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/Funds/FundsList/FundsList.js, src/Groups/GroupsList/GroupsList.js, src/Ledger/LedgerList/LedgersList.js, src/Transactions/TransactionsList/TransactionsList.js
https://issues.folio.org/browse/UIF-371 …
=> UIF-371 Select filter should announce the number of Results in the Results List pane header

CHANGELOG.md, package.json, src/Ledger/LedgerDetails/ExportSettingsModal/ExportSettingsModal.js, src/Ledger/LedgerDetails/ExportSettingsModal/ExportSettingsModal.test.js, src/Ledger/LedgerDetails/ExportSettingsModal/index.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/common/DetailsActions/DetailsExportAction/DetailsExportAction.js, src/common/DetailsActions/DetailsExportAction/DetailsExportAction.test.js, src/common/DetailsActions/DetailsExportAction/index.js, src/common/DetailsActions/index.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-365 …
=> UIF-365 Display export action for ledger

CHANGELOG.md, package.json, src/common/const/constants.js
=> UIF-373 Release v3.1.1

CHANGELOG.md, src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupExpenseClasses/GroupExpenseClasses.js, src/Groups/constants.js, src/Ledger/CreateLedgerFiscalYear/CreateLedgerFiscalYear.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/Ledger/LedgerForm/LedgerForm.js, src/Ledger/LedgerList/LedgersList.js, src/Ledger/constants.js, src/Transactions/TransactionDetails/TransactionInformation/SourceValue/useSourceLink.js, src/common/ExpenseClasses/ExpenseClasses.js
https://issues.folio.org/browse/UIF-376 …
=> UIF-376 module warnings analysis

CHANGELOG.md, src/Ledger/LedgerDetails/ExportSettingsModal/constants.js
https://issues.folio.org/browse/UIF-384 …
=> UIF-384 Identify record type for common fields in budget export

CHANGELOG.md, src/FiscalYears/FiscalYearDetails/FiscalYearDetailsContainer.js, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/FiscalYears/FiscalYearsList/FiscalYearsListContainer.js, src/FiscalYears/FiscalYearsList/FiscalYearsListLastMenu.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundsList/FundsList.js, src/Funds/FundsList/FundsListContainer.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupsList/GroupsList.js, src/Groups/GroupsList/GroupsListContainer.js, src/Groups/GroupsList/GroupsListLastMenu.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/Ledger/LedgerList/LedgerListContainer.js, src/Ledger/LedgerList/LedgersList.js
https://issues.folio.org/browse/UIF-390 …
=> UIF-390 Deleted item name remains in the list

CHANGELOG.md, src/Ledger/RolloverLedger/RolloverLedger.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-393 …
=> UIF-393 Add test rollover action to rollover settings

src/Ledger/RolloverLedger/RolloverLedgerContainer.js, src/Ledger/RolloverLedger/hooks/useUnpaidInvoices/useUnpaidInvoices.js
=> UIF-378 fix query

CHANGELOG.md, package.json, src/Ledger/RolloverLedger/RolloverLedger.js, src/Ledger/RolloverLedger/RolloverLedger.test.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, src/Ledger/RolloverLedger/hooks/useUnpaidInvoices/useUnpaidInvoices.js, src/Ledger/constants.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-395 …
=> UIF-395 FY rollover test confirmation modal

CHANGELOG.md, src/Ledger/RolloverLedger/UnpaidInvoiceListModal/UnpaidInvoiceListModal.js, src/Ledger/RolloverLedger/UnpaidInvoiceListModal/UnpaidInvoiceListModal.test.js, src/Ledger/RolloverLedger/hooks/index.js, src/Ledger/RolloverLedger/hooks/useUnpaidInvoices/useUnpaidInvoices.js, src/Ledger/RolloverLedger/hooks/useUnpaidInvoicesExport/index.js, src/Ledger/RolloverLedger/hooks/useUnpaidInvoicesExport/useUnpaidInvoicesExport.js, src/Ledger/RolloverLedger/hooks/useUnpaidInvoicesExport/useUnpaidInvoicesExport.test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-394 …
=> UIF-394 Export list of unpaid invoices

CHANGELOG.md, src/Ledger/Ledger.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.test.js, src/Ledger/RolloverLedger/hooks/useRolloverData/useRolloverData.test.js, src/Ledger/RolloverLogs/RolloverLogs.js, src/Ledger/RolloverLogs/RolloverLogs.test.js, src/Ledger/RolloverLogs/index.js, src/Transactions/CreateTransaction/CreateTransactionContainer.test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-396 …
=> UIF-396 Add Rollover logs action to Ledger menu

CHANGELOG.md, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-403 …
=> UIF-403 Fix typo

CHANGELOG.md, src/Ledger/RolloverLedger/UnpaidInvoiceListModal/UnpaidInvoiceListModal.js, src/Ledger/RolloverLedger/UnpaidInvoiceListModal/UnpaidInvoiceListModal.test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-399 …
=> UIF-399 Add message to unpaid invoices modal

CHANGELOG.md, src/Funds/hooks/useBudgetsFiscalYears/useBudgetsFiscalYears.js
https://issues.folio.org/browse/UIF-402 …
=> UIF-402 'New' button for 'Planned budget' unexpected behavior

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIF-406 …
=> UIF-406 Add missed perm in Settings

CHANGELOG.md, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.test.js, src/Ledger/RolloverLedger/hooks/index.js, src/Ledger/RolloverLedger/hooks/useRolloverErrorHandler/index.js, src/Ledger/RolloverLedger/hooks/useRolloverErrorHandler/useRolloverErrorHandler.js, src/Ledger/RolloverLedger/hooks/useRolloverErrorHandler/useRolloverErrorHandler.test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-412
Currently, when an error occurred during rollover start, it always show generic message to user.
Add handler for rollover errors to support different error codes. Use react hooks to isolate reusable functionality.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
=> UIF-412 Update the error for rollover uniqueness

package.json
https://issues.folio.org/browse/UIF-415 …
=> UIF-415 Add permission to load rollover budgets results

CHANGELOG.md, src/Ledger/RolloverLedger/RolloverLedger.css, src/Ledger/RolloverLedger/RolloverLedger.js
https://issues.folio.org/browse/UIF-417
Adjust a gap between rollover buttons
While it's …
=> UIF-417 UX: Spacing of rollover buttons on Finance app

CHANGELOG.md, package.json, src/settings/ExpenseClassSettings/ExpenseClassSettings.js, src/settings/FundTypeSettings/FundTypeSettings.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-408 …
=> UIF-408 Provide local translations to `ControlledVocab`

CHANGELOG.md, package.json, src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupDetails/GroupDetailsContainer.test.js, src/Groups/GroupDetails/GroupInformation/GroupInformation.js, src/Groups/GroupDetails/GroupInformation/GroupInformation.test.js, src/Groups/GroupDetails/utils.js, src/Groups/GroupDetails/utils.test.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-419
Users would like the most recent (i.e. current) fiscal year to display first
- add query to fetch group related ledgers (required to get current fiscal years)
- fetch current fiscal year for each ledger in the group ([API](https://s3.amazonaws.com/foliodocs/api/mod-finance/r/ledgers.html#finance_ledgers__id__current_fiscal_year_get))
- group fiscal years by "current" and "previous" to show in `Select` ([requirement](https://issues.folio.org/browse/UIF-419?focusedCommentId=148053&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-148053))
- sort fiscal years by `periodStart` and `series`
- update unit tests
<details>
<summary>Preview</summary>
</details>
Before merging this PR, please go through the following list and …
=> UIF-419 Previous fiscal year selected by default when viewing group records

CHANGELOG.md, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-422 …
=> UIF-422 Handle fiscal year code validation error `invalidFiscalYearCode`

CHANGELOG.md, src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/Transactions/CreateTransaction/CreateTransactionContainer.test.js, src/common/utils/getFundActiveBudget.js, src/common/utils/getFundActiveBudget.test.js, src/common/utils/index.js
https://issues.folio.org/browse/UIF-414
To display the budget of foreign fund-recipient in toast message, a query must be made to obtain the current budget of that fund.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …
=> UIF-414 Incorrect fund name in the toast message for successful moving allocation

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIF-423 …
=> UIF-423 loose plugin dependencies permit incompatible versions

CHANGELOG.md, src/Ledger/LedgerList/LedgersList.js, src/index.js
https://issues.folio.org/browse/UIF-424
Provide `resetFilters` state on location change to use hook for reset active filters …
=> UIF-424 No results found shown after return to search page

package.json
https://issues.folio.org/browse/UIF-414 …
=> UIF-414 add missed permission to get fund budget

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIF-426 …
=> Release v3.3.2

CHANGELOG.md, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/FiscalYears/FiscalYearsList/FiscalYearsList.test.js, src/Funds/FundsList/FundsList.js, src/Groups/GroupsList/GroupsList.js, src/Ledger/LedgerList/LedgersList.js, src/Ledger/LedgerList/LedgersList.test.js, src/Transactions/TransactionsList/TransactionsList.js, src/common/hooks/useSelectedRow/index.js, src/common/hooks/useSelectedRow/useSelectedRow.js, src/common/hooks/useSelectedRow/useSelectedRow.test.js
https://issues.folio.org/browse/UIF-410
- format one of list's column to `<TextLink />`, which will navigate to the details pane
- resolve 'JSX props should not use arrow functions' code smells (sonarcloud)
- update unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> UIF-410 Results List | Hyperlink one column to improve accessibility

translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-427 …
=> UIF-427 fix message typo

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIF-430 …
=> UIF-430 bump stripes to 8.0.0 for Orchid/2023-R1

CHANGELOG.md, src/FiscalYears/FiscalYearDetails/FiscalYearInformation/FiscalYearInformation.js, src/FiscalYears/FiscalYearForm/FiscalYearForm.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-357 …
=> UIF-357 Display FY start/end in UTC

CHANGELOG.md, package.json, src/FiscalYears/FiscalYearDetails/FiscalYearInformation/FiscalYearInformation.js
=> Release v4.0.3

CHANGELOG.md, src/Ledger/RolloverLogs/RolloverLogsFilters/RolloverLogsFilters.test.js, src/Transactions/TransactionsList/TransactionsFilters/TransactionsFilters.test.js
https://issues.folio.org/browse/UIF-453
Avoid private paths in stripes-core imports.
=> UIF-453: Avoid private paths in stripes-core imports

CHANGELOG.md, src/Ledger/RolloverLogs/RolloverLogLink/RolloverLogLink.js
=> UIF-455 After performing the test rollover, only the last 10 budgets

CHANGELOG.md, package.json
=> Release v4.0.4

CHANGELOG.md, src/Ledger/RolloverLogs/RolloverLogLink/RolloverLogLink.js, src/Ledger/RolloverLogs/RolloverLogLink/RolloverLogLink.test.js
=> UIF-415 Download budget results for failed rollovers

CHANGELOG.md, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.test.js
[UIF-465](https://issues.folio.org/browse/UIF-465) -
- Check if there is already rollover with `commit` status which is the same fiscal year id.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number …
=> UIF-465: check if rollover is already exist

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
[UIF-471](https://issues.folio.org/browse/UIF-471) - Update Node.js to v18 in GitHub Actions …
=> UIF-471: Update Node.js to v18 in GitHub Actions

CHANGELOG.md, package.json, src/settings/ExpenseClassSettings/ExpenseClassSettings.js, src/settings/ExpenseClassSettings/ExpenseClassSettings.test.js, src/settings/FinanceSettings.js, src/settings/FundTypeSettings/FundTypeSettings.js, src/settings/FundTypeSettings/FundTypeSettings.test.js, translations/ui-finance/en.json
[UIF-442](https://issues.folio.org/browse/UIF-442) - add permissions and disable action buttons
https://github.com/folio-org/ui-finance/assets/116072773/0670bc30-08a0-4eef-b3dd-2c135476d782
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
=> UIF-442: Need new permission(s) to view Finance settings in UI

CHANGELOG.md, src/Transactions/CreateTransaction/hooks/useCreateTransactionFlow.js, src/Transactions/CreateTransaction/utils.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-464
Add negative amount check for the decrease allocation transaction type in the flow.
https://github.com/folio-org/ui-finance/assets/88109087/d9bcae58-e4de-4c4d-a1c4-ba9685171a3d …
=> UIF-464 Show an alert when decreasing allocation results in a negative available amount

package.json
[UIF-473](https://issues.folio.org/browse/UIF-473) - add `organizations.organizations.collection.get` sub permission …
=> UIF-473: add sub permission for support donors list

CHANGELOG.md, src/Funds/FundDetails/FundDetails.js, src/Funds/FundForm/FundForm.js, src/Funds/FundForm/FundFormContainer.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-482
Add a checkbox field for the form and details view.
Uploading chrome_5YbzV4KRMe.mp4… …
=> UIF-482 Designate funds as location use restricted

src/Funds/FundForm/FundForm.js
[UIF-473](https://issues.folio.org/browse/UIF-473) - fix donors list update issue
https://github.com/folio-org/ui-finance/assets/116072773/88d6d120-91cb-4852-b7b2-8f3bac7c9f84
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UIF-473: fix donors list updating issue

src/Funds/FundForm/FundLocations/FundLocations.js
https://issues.folio.org/browse/UIF-484 …
=> UIF-484 Remove initial filters for find locations lookup

CHANGELOG.md, package.json, src/components/Budget/BudgetView/BudgetViewContainer.js, src/components/Budget/BudgetView/BudgetViewContainer.test.js, src/components/Budget/BudgetView/utils.js, test/jest/__mock__/index.js, test/jest/__mock__/resizeObserver.mock.js, translations/ui-finance/en.json
https://issues.folio.org/browse/UIF-491
https://github.com/folio-org/ui-finance/assets/88109087/0fb1d3fd-39cf-4eb1-a42d-ed2c88528351 …
=> UIF-491 Allow user to recalculate budgets based on conducted transactions when desired

CHANGELOG.md, package.json, src/components/Budget/BudgetView/BudgetViewContainer.js, src/components/Budget/BudgetView/BudgetViewContainer.test.js, src/components/Budget/BudgetView/utils.js, test/jest/__mock__/index.js, test/jest/__mock__/resizeObserver.mock.js, translations/ui-finance/en.json
Propagate changes from develop branch
https://github.com/folio-org/ui-finance/pull/779
https://github.com/folio-org/ui-finance/pull/783
=> Sprint 183 - UIF-491

CHANGELOG.md, src/common/ExpenseClasses/ExpenseClasses.js
https://folio-org.atlassian.net/browse/UIF-509 …
=> UIF-509 Incorrect Display of Expense Class Percent

CHANGELOG.md, package.json, src/Transactions/TransactionDetails/TransactionDetails.js, src/Transactions/TransactionDetails/TransactionDetails.test.js, src/Transactions/TransactionDetails/TransactionDetailsContainer.js, src/Transactions/TransactionDetails/TransactionDetailsContainer.test.js, src/common/hooks/index.js, src/common/hooks/useOrder/index.js, src/common/hooks/useOrder/useOrder.js, src/common/hooks/useOrder/useOrder.test.js
https://folio-org.atlassian.net/browse/UIF-503
Init PR: #785 
In the preceding PR (#785), the workflow status of the order was assessed based on the source's transaction data. Nonetheless, this data lacks the most recent order updates, which necessitates additional order information to be loaded for encumbrances.
Use the `react-query` hook to fetch the order by ID from the encumbrance source order.
https://github.com/folio-org/ui-finance/assets/88109087/ab0878a0-033b-4e13-b1f2-c92faecaa1aa
- What other modules will these …
=> UIF-503 Check workflow status of order in the encumbrance pane actions

CHANGELOG.md, src/FiscalYears/FiscalYearsList/FiscalYearsList.js, src/Funds/FundsList/FundsList.js, src/Groups/GroupsList/GroupsList.js, src/Ledger/LedgerList/LedgersList.js, src/Transactions/TransactionsList/TransactionsList.js, src/common/hooks/index.js, src/common/hooks/useResultsPageTitle/index.js, src/common/hooks/useResultsPageTitle/useResultsPageTitle.js, src/common/hooks/useResultsPageTitle/useResultsPageTitle.test.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-501
UX: Provide a document title based on the active search query.
Result pages (with search):
- Fiscal years
- Ledgers
- Groups
- Funds
- Transactions
Use `<TitleManager />` from `stripes-core`.
https://github.com/folio-org/ui-finance/assets/88109087/aaafde62-991f-4788-a42c-dfa1bc338efb
Ideally all of the PRs …
=> UIF-501 UX Consistency > Search results > Update HTML page title with search term entered

package.json
bump up `stripes-acq-components` version to ~5.1.0 and `stripes-data-transfer-components` version to `~6.1.0`
=> Bump up `stripes-acq-components` version to ~5.1.0 and `stripes-data-transfer-components` version to `~6.1.0`

CHANGELOG.md, src/FiscalYears/FiscalYearForm/FiscalYearForm.js, src/FiscalYears/FiscalYearForm/FiscalYearForm.test.js, src/Funds/FundForm/FundForm.js, src/Funds/FundForm/FundForm.test.js, src/Groups/GroupForm/GroupForm.js, src/Groups/GroupForm/GroupForm.test.js, src/Ledger/LedgerForm/LedgerForm.js, src/Ledger/LedgerForm/LedgerForm.test.js, src/components/Budget/BudgetForm/BudgetForm.js, src/components/Budget/BudgetForm/BudgetForm.test.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-447
To support UX consistency, use translation key so that if the button label changes then no additional development is required: `stripes-components.saveAndClose`
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
=> UIF-447 Utilize the translation key from `stripes-components` for the "Save & Close" button label

CHANGELOG.md, src/FiscalYears/FiscalYearDetails/FiscalYearDetails.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Groups/GroupDetails/GroupDetails.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/Ledger/RolloverLedger/RolloverLedgerView/RolloverLedgerView.js, src/Transactions/TransactionDetails/TransactionDetails.js
https://folio-org.atlassian.net/browse/UIF-502
https://github.com/folio-org/ui-finance/assets/88109087/128668a2-e5c7-4c23-bbd6-9b85c19a7061 …
=> UIF-502 UX Consistency: HTML page title display when third pane (detail record) displays

CHANGELOG.md, package.json, src/Funds/FundForm/FundForm.js, src/Funds/FundForm/FundLocations/FundLocations.js, src/Funds/FundForm/FundLocations/FundLocations.test.js, src/Funds/FundForm/FundLocations/FundLocationsList/FundLocationsList.js, src/Funds/FundForm/FundLocations/FundLocationsList/FundLocationsList.test.js
https://folio-org.atlassian.net/browse/UIF-518
BE updates: https://github.com/folio-org/mod-finance/pull/244/files
Update form field name and normalize data.
https://github.com/folio-org/ui-finance/assets/88109087/e7d0118c-4089-428f-bab5-5cafc8eb7700
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIF-518 Apply changes in the fund schema for the locations field

src/Ledger/LedgerDetails/ExportSettingsModal/utils/createExportReport.js, src/common/const/constants.js
https://folio-org.atlassian.net/browse/UIF-498
Here we added additional field to export csv
note: Changelog was updated in previous PR
=> UIF-498: Export "Credited" total in csv export with other budget data

CHANGELOG.md, src/Ledger/LedgerDetails/LedgerDetailsContainer.js
https://folio-org.atlassian.net/browse/UIF-539 …
=> UIF-539 Misleading message when current fiscal year lapses for a ledger

CHANGELOG.md, src/Ledger/RolloverLedger/UnpaidInvoiceListModal/UnpaidInvoiceListModal.js, src/Transactions/TransactionDetails/TransactionInformation/TransactionInformation.js, src/common/ExpenseClasses/ExpenseClasses.js, src/common/FinancialSummary/FinancialActivity/FinancialActivity.js, src/common/FinancialSummary/FinancialSummary.js, src/common/FinancialSummary/FundingInformation/FundingInformation.js, src/common/FinancialSummary/Overages/Overages.js, src/components/ConnectionListing/ConnectionListing.js
[UIF-540:](https://folio-org.atlassian.net/browse/UIF-540) Display numbers on record views in parentheses when they are negative
https://github.com/user-attachments/assets/931ae9ce-33eb-4091-9272-5405bf527571
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …
=> UIF-540: Display numbers on record views in parentheses when they are negative

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, src/Transactions/TransactionsList/TransactionsFilters/TransactionsFilters.js, src/Transactions/constants.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-535
https://github.com/user-attachments/assets/b52df8a2-d1dc-403c-aa56-54a50cc3f7b1 …
=> Add filter to transactions view for 'Encumbrance status'

CHANGELOG.md, src/Transactions/CreateTransaction/CreateTransactionContainer.test.js, src/Transactions/CreateTransaction/hooks/useCreateTransactionErrorHandler.js, src/Transactions/CreateTransaction/hooks/useCreateTransactionErrorHandler.test.js, src/Transactions/constants.js, translations/ui-finance/en.json
[UIF-543:](https://folio-org.atlassian.net/browse/UIF-543) add error handling for the `budgetRestrictedExpendituresError` error code
https://github.com/user-attachments/assets/ce127a85-ee9f-4116-be2e-84f0b7ab575d …
=> UIF-543: add error handling for the `budgetRestrictedExpendituresError` error code

CHANGELOG.md, src/FiscalYears/FiscalYearDetails/FiscalYearDetails.js, src/FiscalYears/FiscalYearDetails/FiscalYearInformation/FiscalYearInformation.js, src/Funds/FundDetails/FundDetailsContainer.js, src/Funds/FundForm/FundForm.js, src/Funds/FundForm/FundForm.test.js, src/Funds/FundForm/FundFormContainer.js, src/Transactions/CreateTransaction/CreateTransactionContainer.test.js, src/Transactions/CreateTransaction/CreateTransactionModal.test.js, src/common/hooks/index.js, src/common/hooks/useLedgerCurrentFiscalYear/index.js, src/common/hooks/useLedgerCurrentFiscalYear/useLedgerCurrentFiscalYear.js, src/common/hooks/useLedgerCurrentFiscalYear/useLedgerCurrentFiscalYear.test.js, src/components/Budget/BudgetForm/BudgetForm.js, src/components/Budget/BudgetForm/BudgetInformationFields.js, src/components/Budget/BudgetView/BudgetInformation.js
https://folio-org.atlassian.net/browse/UIF-538
https://github.com/user-attachments/assets/b274c8fe-f131-4f94-b007-2b9b5b6895ff …
=> UIF-538 Display currency on Fiscal Year and Budget

CHANGELOG.md, src/Transactions/TransactionsList/hooks/useBuildQuery/useBuildQuery.js, src/Transactions/TransactionsList/hooks/useBuildQuery/useBuildQuery.test.js, src/Transactions/TransactionsList/hooks/useTransactions/useTransactions.test.js
https://folio-org.atlassian.net/browse/UIF-555
https://github.com/user-attachments/assets/e98d5bec-b663-420f-ab9b-13e7a531af53 …
=> UIF-555 Fix initial transactions list sorting field name

CHANGELOG.md, package.json, src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/Transactions/CreateTransaction/CreateTransactionContainer.test.js, src/common/const/api.js, src/common/const/constants.js, src/common/hooks/index.js, src/common/hooks/useBatchTransactionsMutation/index.js, src/common/hooks/useBatchTransactionsMutation/useBatchTransactionsMutation.js, src/common/hooks/useBatchTransactionsMutation/useBatchTransactionsMutation.test.js, src/common/resources/transaction.js, test/bigtest/network/configs/transactions.js
[UIF-519](https://folio-org.atlassian.net/browse/UIF-519): Replace deprecated calls to transaction API
https://github.com/user-attachments/assets/764fa9d6-040d-4b05-88c3-2dcb2bee4cf3
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
=> UIF-519: Replace deprecated calls to transaction API

src/Transactions/CreateTransaction/CreateTransactionContainer.js
[UIF-519](https://folio-org.atlassian.net/browse/UIF-519): fix - update success message with missing amount
https://github.com/user-attachments/assets/5cba96ce-50a8-469a-82bd-fc2fbd3949be
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
=> UIF-519: fix - update success message with amount (Follow up)

CHANGELOG.md, package.json, src/Transactions/TransactionsList/TransactionsFilters/TransactionsFilters.test.js
=> UIF-566 add missed permissions

CHANGELOG.md, package.json, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupDetails/utils.js, src/Groups/GroupDetails/utils.test.js
=> UIF-587 Hide future FYs from group details view

src/components/BatchAllocations/BatchAllocationLogDetails/BatchAllocationLogDetails.js, src/components/BatchAllocations/BatchAllocationLogs/utils.js, src/components/BatchAllocations/UploadBatchAllocations/UploadBatchAllocations.js, src/components/BatchAllocations/UploadBatchAllocations/buildInitialValues.js, src/components/BatchAllocations/hooks/useBatchAllocationLog/useBatchAllocationLog.js, src/components/BatchAllocations/hooks/useBatchAllocationLogs/useBatchAllocationLogs.js, src/components/BatchAllocations/utils.js, translations/ui-finance/en.json
=> UIF-531 fix batch allocation logs issues

src/components/BatchAllocations/BatchAllocationLogs/utils.js
=> UIF-541 fix navigation after filter change

CHANGELOG.md, src/Groups/GroupDetails/GroupDetails.js, src/Groups/GroupDetails/GroupDetailsContainer.js, src/Groups/GroupsList/GroupsList.js, src/Groups/GroupsList/GroupsListLastMenu.js, src/Groups/GroupsList/GroupsListLastMenu.test.js, src/Ledger/LedgerDetails/LedgerDetails.js, src/Ledger/LedgerDetails/LedgerDetailsContainer.js, src/Ledger/LedgerList/LedgerListLastMenu.js, src/Ledger/LedgerList/LedgerListLastMenu.test.js, src/Ledger/LedgerList/LedgersList.js, src/common/components/batch-allocation/AllocationToolsMenuSection/AllocationToolsMenuSection.js, src/components/BatchAllocations/BatchAllocationLogs/BatchAllocationLogs.js
=> UIF-588 Move View batch allocation logs action to list level

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UIF-574
https://folio-org.atlassian.net/browse/UIF-575
=> UIF-574 UIF-575 Migrate react-intl and stripes dependencies

CHANGELOG.md, src/common/components/batch-allocation/DownloadAllocationWorksheetModal/DownloadAllocationWorksheetModal.js, src/common/components/batch-allocation/UploadAllocationWorksheetModal/utils/validators.js, src/common/const/constants.js, src/common/utils/composeValidators.js, src/components/BatchAllocations/BatchAllocationsForm/BatchAllocationsForm.js, src/components/BatchAllocations/BatchAllocationsForm/utils.js, src/components/BatchAllocations/BatchAllocationsForm/utils.test.js, src/components/BatchAllocations/CreateBatchAllocations/CreateBatchAllocations.js, src/components/BatchAllocations/CreateBatchAllocations/CreateBatchAllocations.test.js, src/components/BatchAllocations/UploadBatchAllocations/UploadBatchAllocations.js, src/components/BatchAllocations/UploadBatchAllocations/UploadBatchAllocations.test.js, src/components/BatchAllocations/UploadBatchAllocations/buildInitialValues.js, src/components/BatchAllocations/constants.js, src/components/BatchAllocations/hooks/useBatchAllocationFormHandler/useBatchAllocationFormHandler.js, src/components/BatchAllocations/hooks/useBatchAllocationFormHandler/useBatchAllocationFormHandler.test.js, src/components/BatchAllocations/hooks/useBatchAllocationFormatter/useBatchAllocationFormatter.js, src/components/BatchAllocations/hooks/useBatchAllocationFormatter/validators.js, src/components/BatchAllocations/hooks/useBatchAllocationMutation/useBatchAllocationMutation.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-589
https://github.com/user-attachments/assets/e40bdd6b-3af9-445f-bcf4-6a24aa6e9257 …
=> UIF-589 Batch allocation bugs/enhancements

CHANGELOG.md, src/Transactions/TransactionsList/hooks/useBuildQuery/useBuildQuery.js
=> UIF-593 Fix transaction sorting by amount

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/Transactions/CreateTransaction/CreateTransactionModal.js, src/Transactions/CreateTransaction/CreateTransactionModal.test.js, src/Transactions/CreateTransaction/createTransactionFlow.js, src/Transactions/CreateTransaction/hooks/useCreateTransactionFlow.js, src/Transactions/CreateTransaction/utils.js, src/components/BatchAllocations/BatchAllocationsForm/BatchAllocationsForm.js, src/components/BatchAllocations/CreateBatchAllocations/CreateBatchAllocations.js, src/components/BatchAllocations/UploadBatchAllocations/UploadBatchAllocations.js, src/components/BatchAllocations/UploadBatchAllocations/UploadBatchAllocations.test.js, src/components/BatchAllocations/UploadBatchAllocations/buildInitialValues.js, src/components/BatchAllocations/constants.js, src/components/BatchAllocations/hooks/useBatchAllocationFormatter/useBatchAllocationFormatter.js, src/components/Budget/BudgetView/BudgetView.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-576
https://github.com/user-attachments/assets/5ab8c14d-b366-4745-9b63-f191c32609b3 …
=> UIF-576 Prevent negative total allocations in budgets

src/components/Budget/AddBudgetModal/AddBudgetModalForm.js
https://folio-org.atlassian.net/browse/UIF-573 …
=> UIF-573 Include 0 as a valid number

src/components/BatchAllocations/BatchAllocationsForm/BatchAllocationsForm.js, src/components/BatchAllocations/UploadBatchAllocations/buildInitialValues.js, src/components/BatchAllocations/hooks/useBatchAllocationFormatter/useBatchAllocationFormatter.js, src/components/BatchAllocations/utils.js
https://folio-org.atlassian.net/browse/UIF-589
=> UIF-589 Fix issue with form rerenders

src/components/BatchAllocations/BatchAllocationLogs/BatchAllocationLogsList.js, src/components/BatchAllocations/utils.js
https://folio-org.atlassian.net/browse/UIF-589
=> UIF-589 Exclude file extension duplication

CHANGELOG.md, src/Groups/constants.js, src/common/utils/fetchGroupCurrentFiscalYears.js, src/common/utils/fetchGroupCurrentFiscalYears.test.js, src/common/utils/fetchLedgerCurrentFiscalYear.js, src/common/utils/fetchLedgerCurrentFiscalYear.test.js, src/common/utils/index.js, src/components/BatchAllocations/BatchAllocationsForm/BatchAllocationsForm.js, src/components/BatchAllocations/CreateBatchAllocations/CreateBatchAllocations.js, src/components/BatchAllocations/CreateBatchAllocations/CreateBatchAllocations.test.js, src/components/BatchAllocations/UploadBatchAllocations/UploadBatchAllocations.js, src/components/BatchAllocations/UploadBatchAllocations/UploadBatchAllocations.test.js, src/components/BatchAllocations/hooks/index.js, src/components/BatchAllocations/hooks/useSourceCurrentFiscalYears/index.js, src/components/BatchAllocations/hooks/useSourceCurrentFiscalYears/useSourceCurrentFiscalYears.js, src/components/BatchAllocations/hooks/useSourceCurrentFiscalYears/useSourceCurrentFiscalYears.test.js, src/components/BatchAllocations/utils.js, src/components/BatchAllocations/utils.test.js
https://folio-org.atlassian.net/browse/UIF-596
Check if selected fiscal year is future one.
https://github.com/user-attachments/assets/136a553e-280c-4e3a-92e8-e5ca3cfd38db
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …
=> UIF-596 Automatically set status Planned for budgets in a future fiscal year

CHANGELOG.md, src/Funds/FundForm/FundLocations/FundLocationsList/FundLocationsList.js
https://folio-org.atlassian.net/browse/UIF-561
https://github.com/user-attachments/assets/a39378da-e074-4241-aa7a-ae317379e772 …
=> UIF-561 Display only assigned for a user affiliations in the lookup

CHANGELOG.md, src/Transactions/CreateTransaction/CreateTransactionContainer.js
https://folio-org.atlassian.net/browse/UIF-604
https://github.com/user-attachments/assets/2e9571cc-a12b-47fb-bc74-86f8cc9a0738 …
=> UIF-604 Fix handling of error response on transaction create flow

CHANGELOG.md, src/settings/ExchangeRateSourceSettings/ExchangeRateSourceForm.js, src/settings/ExchangeRateSourceSettings/ExchangeRateSourceSettings.test.js, src/settings/ExchangeRateSourceSettings/constants.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-605
Store the list of supported exchange rate providers in the code. Set up the config for the form field based on provider requirements (API key, API secret).
https://github.com/user-attachments/assets/073e7440-c097-47f7-ae78-b90ed1982eb5
Ideally all of the PRs involved in breaking changes would be merged in the …
=> UIF-605 Add a new field providerType to exchange rate source settings

CHANGELOG.md, package.json, src/settings/ExchangeRateSourceSettings/ExchangeRateSourceForm.js, src/settings/ExchangeRateSourceSettings/ExchangeRateSourceSettings.js, src/settings/FinanceSettings.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-583
Let's consider `Settings (Finance): Manage external exchange rate source`, `Settings (Finance): View, edit, create, delete`, and `Settings (Finance): View settings` permissions as `A`, `B`, and `C` correspondingly.
Cases:
- A user has `A`, but does **NOT** have (`B` **OR** `C`) ---> user can **NOT** see any settings
- A user has `A` and `C`, but **NOT** `B` ---> user can **ONLY VIEW** "Exchange rate source" settings
- A user has `A` and `B` ---> user can fully manage "Exchange rate source" settings
- A user has `B` or `C`, but **NOT** `A` ---> A user can **NOT** see "Exchange rate source" settings
https://github.com/user-attachments/assets/939daf1e-e6f0-445f-822c-19b6c35a75e5
Before merging this PR, please go through the following list and …
=> UIF-583 Capabilities for setting up alternate exchange rate source

CHANGELOG.md, src/common/utils/generateBudgetsReport.js, src/common/utils/generateBudgetsReport.test.js
=> UIF-607 Do not fail rollover results export when no rollover budgets are created

CHANGELOG.md, src/Ledger/RolloverLedger/RolloverFiscalYears.js, src/Ledger/RolloverLedger/RolloverLedgerContainer.js, src/Ledger/RolloverLedger/RolloverLedgerView/RolloverFiscalYearsView/RolloverFiscalYearsView.js, test/jest/fixtures/rollover/rollover.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-611
https://github.com/user-attachments/assets/a7a560bb-189f-4dd6-8f1a-85becd4f05fa …
=> UIF-611 Remove expenditure limit toggle from rollover settings

src/Transactions/CreateTransaction/CreateTransactionContainer.js, src/Transactions/CreateTransaction/CreateTransactionContainer.test.js, src/Transactions/CreateTransaction/CreateTransactionModal.js, src/Transactions/CreateTransaction/CreateTransactionModal.test.js, src/Transactions/CreateTransaction/utils.js, src/common/hooks/index.js, src/common/hooks/useBudgetByFundAndFY/index.js, src/common/hooks/useBudgetByFundAndFY/useBudgetByFundAndFY.js, src/common/hooks/useBudgetByFundAndFY/useBudgetByFundAndFY.test.js, src/common/utils/getBudgetByFundAndFY.js, src/common/utils/index.js, src/components/BatchAllocations/CreateBatchAllocations/CreateBatchAllocations.test.js, src/components/BatchAllocations/UploadBatchAllocations/UploadBatchAllocations.test.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-621
Enhance: #918 
Current implementation checks the total allocation after a transaction only for viewing a budget, but it is expected to validate another budget as well.
Fetch a second budget used in a transaction to validate a new total allocation value.
https://github.com/user-attachments/assets/3f1aac73-c440-4750-8b52-bab36789f46c
- Do PRs …
=> UIF-621 Validate both budgets during allocation

CHANGELOG.md, src/settings/ExchangeRateSourceSettings/ExchangeRateSourceForm.js, src/settings/ExchangeRateSourceSettings/ExchangeRateSourceSettings.test.js, src/settings/ExchangeRateSourceSettings/constants.js, translations/ui-finance/en.json
https://folio-org.atlassian.net/browse/UIF-623
Based on UAT feedback, exchange rate provider types should be less specific.
- Change `treasury.gov` to `No key required`
- Remove `convera.com`
- Change `currencyapi.com` to `Key required`
https://github.com/user-attachments/assets/72a02535-673f-4727-b778-2044df2fcb62
Ideally all of the PRs involved in …
=> UIF-623 Change labels for exchange rate provider type
